import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadCatalogSource } from "./catalog-source";
import {
  loadReleaseOverrides,
  indexReleaseOverrides,
  resolvePsychubeRelease,
} from "./release-status";
import type { PsychubeEntry } from "./types";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT_FILE = path.join(ROOT, "src/data/psychubes.ts");
const OVERRIDES_FILE = path.join(__dirname, "data/released-overrides.json");
export function buildPsychubes(): void {
  console.log("build-psychubes — compact source + manual overrides\n");
  const source = loadCatalogSource();
  const overrides = loadReleaseOverrides(OVERRIDES_FILE);
  const index = indexReleaseOverrides(overrides, {
    characters: new Set(source.characters.map((entry) => entry.baseId)),
    skins: new Set(
      source.characters.flatMap((entry) =>
        entry.skins
          .filter((skin) => skin.type === "skin")
          .map((skin) => skin.id),
      ),
    ),
    psychubes: new Set(source.psychubes.map((entry) => entry.id)),
  });
  const entries: PsychubeEntry[] = source.psychubes.map(
    ({ glPresent, ...entry }) => ({
      ...entry,
      released: resolvePsychubeRelease(
        glPresent,
        index.psychubes.get(entry.id)?.isReleased,
      ),
    }),
  );
  writeFileSync(
    OUT_FILE,
    "// Generated by scripts/build-psychubes.ts — CN∩GL baseline + manual overrides\n" +
      'import type { PsychubeDef } from "../types/catalog";\n\n' +
      "export const psychubes: PsychubeDef[] = " +
      JSON.stringify(entries, null, 2) +
      ";\n",
  );
  console.log(
    `心相：${entries.length}；未實裝：${entries.filter((entry) => !entry.released).length}`,
  );
}
if (import.meta.url === "file://" + process.argv[1]) buildPsychubes();
