import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadCatalogSource } from "./catalog-source";
import { assertKnownCapabilities, loadCatalogPolicy } from "./catalog-policy";
import {
  parseReleaseOrderSources,
  recalculateReleaseOrder,
} from "./recalculate-order";
import {
  loadReleaseOverrides,
  indexReleaseOverrides,
  resolveCharacterRelease,
  resolveSkinRelease,
} from "./release-status";
import type { CharacterEntry } from "./types";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT_FILE = path.join(ROOT, "src/data/characters.ts");
const OVERRIDES_FILE = path.join(__dirname, "data/released-overrides.json");
const RELEASE_ORDER = path.join(__dirname, "data/release-order.json");
const POLICY_FILE = path.join(__dirname, "data/catalog-policy.json");
export function buildCharacters(): void {
  console.log("build-characters — compact source + manual overrides\n");
  const source = loadCatalogSource();
  const overrides = loadReleaseOverrides(OVERRIDES_FILE);
  const policy = loadCatalogPolicy(POLICY_FILE);
  assertKnownCapabilities(
    policy,
    new Set(source.characters.map((entry) => entry.baseId)),
    new Set(source.psychubes.map((entry) => entry.id)),
  );
  const capabilities = new Map(
    policy.characterCapabilities.map((entry) => [entry.baseId, entry]),
  );
  const index = indexReleaseOverrides(overrides, {
    characters: new Set(source.characters.map((entry) => entry.baseId)),
    skins: new Set(
      source.characters.flatMap((entry) =>
        entry.skins
          .filter((skin) => skin.type === "skin")
          .map((skin) => skin.id),
      ),
    ),
    psychubes: new Set(source.psychubes.map((entry) => entry.id)),
  });
  const entries: CharacterEntry[] = source.characters.map(
    ({ glReleased, skins, defaultVariant, ...entry }) => ({
      ...entry,
      releaseOrder: 0,
      released: resolveCharacterRelease(
        glReleased,
        index.characters.get(entry.baseId)?.isReleased,
      ),
      skins: skins.map((skin) => {
        const glPresent = skin.type === "skin" ? skin.glPresent : undefined;
        const { glPresent: _pipelineOnly, ...runtimeSkin } =
          skin as typeof skin & {
            glPresent?: boolean;
          };
        return {
          ...runtimeSkin,
          released: resolveSkinRelease(
            skin.type,
            glPresent,
            index.skins.get(skin.id)?.isReleased,
          ),
        };
      }),
      defaultVariant,
      ...(capabilities.has(entry.baseId)
        ? {
            psychubeSlots: capabilities.get(entry.baseId)!.psychubeSlots,
            exclusivePsychubeIds: capabilities.get(entry.baseId)!
              .exclusivePsychubeIds,
          }
        : {}),
    }),
  );
  const ordered = recalculateReleaseOrder(
    entries,
    parseReleaseOrderSources(JSON.parse(readFileSync(RELEASE_ORDER, "utf-8"))),
  );
  writeFileSync(
    OUT_FILE,
    "// Generated by scripts/build-characters.ts — GL character/skin presence + manual overrides\n" +
      'import type { CharacterDef } from "../types/catalog";\n\n' +
      "export const characters: CharacterDef[] = " +
      JSON.stringify(ordered, null, 2) +
      ";\n",
  );
  console.log(
    `角色：${entries.length}；未實裝：${entries.filter((entry) => !entry.released).length}`,
  );
  console.log(
    `skin：${entries.flatMap((entry) => entry.skins).length}；未實裝：${entries.flatMap((entry) => entry.skins).filter((skin) => !skin.released).length}`,
  );
}
if (import.meta.url === "file://" + process.argv[1]) buildCharacters();
