// Generated by scripts/build-characters.ts — GL character/skin presence + manual overrides
import type { CharacterDef } from "../types/catalog";

export const characters: CharacterDef[] = [
  {
    "id": "3157",
    "baseId": "3157",
    "names": {
      "zh-CN": "纳西索斯",
      "zh-TW": "Narcissus",
      "en-US": "Narcissus",
      "ja-JP": "Narcissus",
      "ko-KR": "Narcissus"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 1,
    "released": false,
    "skins": [
      {
        "id": "315701",
        "type": "default",
        "released": true
      },
      {
        "id": "315702",
        "type": "insight",
        "name": "涟漪的裙裾",
        "nameEn": "Ripples Yet to Bloom",
        "released": true
      }
    ],
    "defaultVariant": "315701"
  },
  {
    "id": "3156",
    "baseId": "3156",
    "names": {
      "zh-CN": "赫多涅",
      "zh-TW": "赫多涅",
      "en-US": "Hedone",
      "ja-JP": "Hedone",
      "ko-KR": "Hedone"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 2,
    "released": false,
    "skins": [
      {
        "id": "315601",
        "type": "default",
        "released": true
      },
      {
        "id": "315602",
        "type": "insight",
        "name": "与过往碰杯",
        "nameEn": "A Cheers to the Past",
        "released": true
      }
    ],
    "defaultVariant": "315601"
  },
  {
    "id": "3149",
    "baseId": "3149",
    "names": {
      "zh-CN": "双生舞伶",
      "zh-TW": "雙生舞伶",
      "en-US": "The Twins",
      "ja-JP": "双子",
      "ko-KR": "쌍둥이"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 3,
    "released": true,
    "skins": [
      {
        "id": "314901",
        "type": "default",
        "released": true
      },
      {
        "id": "314902",
        "type": "insight",
        "name": "异托邦来客",
        "nameEn": "Visitors from \"Utopia\"",
        "released": true
      },
      {
        "id": "314903",
        "type": "skin",
        "name": "可编程挽歌",
        "nameEn": "Programmed Eulogy",
        "released": true
      }
    ],
    "defaultVariant": "314901",
    "psychubeSlots": 2,
    "exclusivePsychubeIds": [
      "1571",
      "1572"
    ]
  },
  {
    "id": "3147",
    "baseId": "3147",
    "names": {
      "zh-CN": "无名者",
      "zh-TW": "無名者",
      "en-US": "Ms. Stranger",
      "ja-JP": "ストレンジャー",
      "ko-KR": "미스 스트레인저"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 4,
    "released": true,
    "skins": [
      {
        "id": "314701",
        "type": "default",
        "released": true
      },
      {
        "id": "314702",
        "type": "insight",
        "name": "无尽且唯一的路",
        "nameEn": "Down a Dark Path",
        "released": true
      },
      {
        "id": "314704",
        "type": "skin",
        "name": "沉影探戈",
        "nameEn": "Waltz of the Depths",
        "released": false
      }
    ],
    "defaultVariant": "314701"
  },
  {
    "id": "3146",
    "baseId": "3146",
    "names": {
      "zh-CN": "小瑞安侬",
      "zh-TW": "小瑞安儂",
      "en-US": "Rhiannon",
      "ja-JP": "リアンノン",
      "ko-KR": "리아논"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 5,
    "released": true,
    "skins": [
      {
        "id": "314601",
        "type": "default",
        "released": true
      },
      {
        "id": "314602",
        "type": "insight",
        "name": "心灵迁徙",
        "nameEn": "The Migration of Her Heart",
        "released": true
      }
    ],
    "defaultVariant": "314601"
  },
  {
    "id": "3145",
    "baseId": "3145",
    "names": {
      "zh-CN": "回声谣",
      "zh-TW": "回聲謠",
      "en-US": "Everecho",
      "ja-JP": "エバーエコー",
      "ko-KR": "에버에코"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 6,
    "released": false,
    "skins": [
      {
        "id": "314501",
        "type": "default",
        "released": true
      },
      {
        "id": "314502",
        "type": "insight",
        "name": "静谧与光明",
        "nameEn": "Silence and Light",
        "released": true
      }
    ],
    "defaultVariant": "314501"
  },
  {
    "id": "3144",
    "baseId": "3144",
    "names": {
      "zh-CN": "珐琅眼",
      "zh-TW": "琺瑯眼",
      "en-US": "Coppélia",
      "ja-JP": "コッペリア",
      "ko-KR": "코펠리아"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 7,
    "released": true,
    "skins": [
      {
        "id": "314401",
        "type": "default",
        "released": true
      },
      {
        "id": "314402",
        "type": "insight",
        "name": "自鸣乐器之歌",
        "nameEn": "Song of the Self-Playing Instrument",
        "released": true
      },
      {
        "id": "314403",
        "type": "skin",
        "name": "醒时声",
        "nameEn": "Sounds that Wake Her",
        "released": true
      }
    ],
    "defaultVariant": "314401"
  },
  {
    "id": "3143",
    "baseId": "3143",
    "names": {
      "zh-CN": "哑谜",
      "zh-TW": "啞謎",
      "en-US": "Enigma",
      "ja-JP": "エニグマ",
      "ko-KR": "이니그마"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 8,
    "released": true,
    "skins": [
      {
        "id": "314301",
        "type": "default",
        "released": true
      },
      {
        "id": "314302",
        "type": "insight",
        "name": "填空题",
        "nameEn": "Cloze Testing",
        "released": true
      },
      {
        "id": "314303",
        "type": "skin",
        "name": "泅与问",
        "nameEn": "To Fathom the Depths",
        "released": false
      }
    ],
    "defaultVariant": "314301"
  },
  {
    "id": "3142",
    "baseId": "3142",
    "names": {
      "zh-CN": "拉莫纳",
      "zh-TW": "拉莫納",
      "en-US": "Ramona",
      "ja-JP": "ラモナ",
      "ko-KR": "라모나"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 9,
    "released": true,
    "skins": [
      {
        "id": "314201",
        "type": "default",
        "released": true
      },
      {
        "id": "314202",
        "type": "insight",
        "name": "灵与花之间",
        "nameEn": "Between Spirits and Blossoms",
        "released": true
      }
    ],
    "defaultVariant": "314201"
  },
  {
    "id": "3141",
    "baseId": "3141",
    "names": {
      "zh-CN": "鹭鸶剪",
      "zh-TW": "鷺鷥剪",
      "en-US": "Paper Heron",
      "ja-JP": "鷺切",
      "ko-KR": "노사전"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 10,
    "released": true,
    "skins": [
      {
        "id": "314101",
        "type": "default",
        "released": true
      },
      {
        "id": "314102",
        "type": "insight",
        "name": "新花故吾",
        "nameEn": "Downstream of Letting Go",
        "released": true
      }
    ],
    "defaultVariant": "314101"
  },
  {
    "id": "3140",
    "baseId": "3140",
    "names": {
      "zh-CN": "奠基石",
      "zh-TW": "奠基石",
      "en-US": "Cornerstone",
      "ja-JP": "コーナーストーン",
      "ko-KR": "코너스톤"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 11,
    "released": false,
    "skins": [
      {
        "id": "314001",
        "type": "default",
        "released": true
      },
      {
        "id": "314002",
        "type": "insight",
        "name": "基桩嵌于构想",
        "nameEn": "Grounded in Imagination",
        "released": true
      }
    ],
    "defaultVariant": "314001"
  },
  {
    "id": "3139",
    "baseId": "3139",
    "names": {
      "zh-CN": "洛伦兹蝴蝶",
      "zh-TW": "洛倫茲蝴蝶",
      "en-US": "Lorentz Butterfly",
      "ja-JP": "ローレンツバタフライ",
      "ko-KR": "로렌츠 버터플라이"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 12,
    "released": true,
    "skins": [
      {
        "id": "313901",
        "type": "default",
        "released": true
      },
      {
        "id": "313902",
        "type": "insight",
        "name": "雨、混沌、翅震颤",
        "nameEn": "Rain, Chaos and Fluttering",
        "released": true
      },
      {
        "id": "313903",
        "type": "skin",
        "name": "致命银弦",
        "nameEn": "Finale in Silver",
        "released": false
      }
    ],
    "defaultVariant": "313901"
  },
  {
    "id": "3137",
    "baseId": "3137",
    "names": {
      "zh-CN": "程和光",
      "zh-TW": "程和光",
      "en-US": "Cheng Heguang",
      "ja-JP": "程和光",
      "ko-KR": "정화광"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 13,
    "released": true,
    "skins": [
      {
        "id": "313701",
        "type": "default",
        "released": true
      },
      {
        "id": "313702",
        "type": "insight",
        "name": "檐外鹭",
        "nameEn": "Breaking Free from a Burning Cage",
        "released": true
      }
    ],
    "defaultVariant": "313701"
  },
  {
    "id": "3135",
    "baseId": "3135",
    "names": {
      "zh-CN": "灰调蓝",
      "zh-TW": "灰調藍",
      "en-US": "Brume",
      "ja-JP": "グレイッシュブルー",
      "ko-KR": "브룸"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 14,
    "released": true,
    "skins": [
      {
        "id": "313501",
        "type": "default",
        "released": true
      },
      {
        "id": "313502",
        "type": "insight",
        "name": "意外停靠",
        "nameEn": "A Wayward Intermission",
        "released": true
      },
      {
        "id": "313503",
        "type": "skin",
        "name": "海盐急速",
        "nameEn": "Full Quack Ahead",
        "released": false
      }
    ],
    "defaultVariant": "313501"
  },
  {
    "id": "3134",
    "baseId": "3134",
    "names": {
      "zh-CN": "贝丽尔",
      "zh-TW": "貝麗爾",
      "en-US": "Beryl",
      "ja-JP": "ベリル",
      "ko-KR": "베릴"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 15,
    "released": true,
    "skins": [
      {
        "id": "313401",
        "type": "default",
        "released": true
      },
      {
        "id": "313402",
        "type": "insight",
        "name": "水上浮光",
        "nameEn": "The Flowing Stream's Luster",
        "released": true
      }
    ],
    "defaultVariant": "313401"
  },
  {
    "id": "3132",
    "baseId": "3132",
    "names": {
      "zh-CN": "告死鸟",
      "zh-TW": "告死鳥",
      "en-US": "Corvus",
      "ja-JP": "コルヴス",
      "ko-KR": "코르부스"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 16,
    "released": true,
    "skins": [
      {
        "id": "313201",
        "type": "default",
        "released": true
      },
      {
        "id": "313202",
        "type": "insight",
        "name": "编织一寸温暖",
        "nameEn": "The Warmth She Knitted",
        "released": true
      },
      {
        "id": "313203",
        "type": "skin",
        "name": "将哀啼也燃尽",
        "nameEn": "Burning Away Tears",
        "released": true
      }
    ],
    "defaultVariant": "313201"
  },
  {
    "id": "3128",
    "baseId": "3128",
    "names": {
      "zh-CN": "卡戎",
      "zh-TW": "卡戎",
      "en-US": "Charon",
      "ja-JP": "カローン",
      "ko-KR": "카론"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 17,
    "released": true,
    "skins": [
      {
        "id": "312801",
        "type": "default",
        "released": true
      },
      {
        "id": "312802",
        "type": "insight",
        "name": "沉默与悲鸣",
        "nameEn": "Wailing Silence",
        "released": true
      },
      {
        "id": "312803",
        "type": "skin",
        "name": "亡者的恩赐",
        "nameEn": "Gift of the Dead",
        "released": true
      }
    ],
    "defaultVariant": "312801"
  },
  {
    "id": "3127",
    "baseId": "3127",
    "names": {
      "zh-CN": "玛尔纱",
      "zh-TW": "瑪爾紗",
      "en-US": "Marsha",
      "ja-JP": "マルシャ",
      "ko-KR": "마샤"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 18,
    "released": true,
    "skins": [
      {
        "id": "312701",
        "type": "default",
        "released": true
      },
      {
        "id": "312702",
        "type": "insight",
        "name": "我曾如此宣誓——",
        "nameEn": "And This I Swear",
        "released": true
      },
      {
        "id": "312703",
        "type": "skin",
        "name": "不熄的怀抱",
        "nameEn": "The Ever-Burning Embrace",
        "released": true
      }
    ],
    "defaultVariant": "312701"
  },
  {
    "id": "3126",
    "baseId": "3126",
    "names": {
      "zh-CN": "玛丽安娜",
      "zh-TW": "瑪麗安娜",
      "en-US": "Sentinel",
      "ja-JP": "センティネル",
      "ko-KR": "센티널"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 19,
    "released": true,
    "skins": [
      {
        "id": "312601",
        "type": "default",
        "released": true
      },
      {
        "id": "312602",
        "type": "insight",
        "name": "孽的锁链",
        "nameEn": "The Shackles of Sin",
        "released": true
      },
      {
        "id": "312603",
        "type": "skin",
        "name": "镜廊宣言",
        "nameEn": "By Reflections Witnessed",
        "released": true
      },
      {
        "id": "312606",
        "type": "skin",
        "name": "称量罪与理",
        "nameEn": "Weighing Sin and Justice",
        "released": true
      }
    ],
    "defaultVariant": "312601"
  },
  {
    "id": "3125",
    "baseId": "3125",
    "names": {
      "zh-CN": "野树莓",
      "zh-TW": "野樹莓",
      "en-US": "Rubuska",
      "ja-JP": "ルブシカ",
      "ko-KR": "루부스카"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 20,
    "released": true,
    "skins": [
      {
        "id": "312501",
        "type": "default",
        "released": true
      },
      {
        "id": "312502",
        "type": "insight",
        "name": "魔笛手之梦",
        "nameEn": "The Piper's Dream",
        "released": true
      },
      {
        "id": "312503",
        "type": "skin",
        "name": "踏影歌",
        "nameEn": "Song of the Shadow Dancer",
        "released": true
      }
    ],
    "defaultVariant": "312501"
  },
  {
    "id": "3124",
    "baseId": "3124",
    "names": {
      "zh-CN": "卡珊德拉",
      "zh-TW": "卡珊卓",
      "en-US": "Kassandra",
      "ja-JP": "カサンドラ",
      "ko-KR": "카산드라"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 21,
    "released": true,
    "skins": [
      {
        "id": "312401",
        "type": "default",
        "released": true
      },
      {
        "id": "312402",
        "type": "insight",
        "name": "湛蓝而闪耀",
        "nameEn": "Radiant in Blue",
        "released": true
      }
    ],
    "defaultVariant": "312401"
  },
  {
    "id": "3123",
    "baseId": "3123",
    "names": {
      "zh-CN": "艾吉奥·奥迪托雷",
      "zh-TW": "埃齊歐·奧迪托雷",
      "en-US": "Ezio Auditore",
      "ja-JP": "エツィオ",
      "ko-KR": "에지오 아디토레"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 22,
    "released": true,
    "skins": [
      {
        "id": "312301",
        "type": "default",
        "released": true
      },
      {
        "id": "312302",
        "type": "insight",
        "name": "信仰，于此跃下",
        "nameEn": "Leap of Faith",
        "released": true
      }
    ],
    "defaultVariant": "312301"
  },
  {
    "id": "3121",
    "baseId": "3121",
    "names": {
      "zh-CN": "莫莉德尔",
      "zh-TW": "莫莉德爾",
      "en-US": "Moldir",
      "ja-JP": "モルダー",
      "ko-KR": "몰디르"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 23,
    "released": true,
    "skins": [
      {
        "id": "312101",
        "type": "default",
        "released": true
      },
      {
        "id": "312102",
        "type": "insight",
        "name": "永不遗忘的",
        "nameEn": "Things Never Forgotten",
        "released": true
      },
      {
        "id": "312103",
        "type": "skin",
        "name": "石头城挽歌",
        "nameEn": "Idyll of the Luberon",
        "released": true
      },
      {
        "id": "312104",
        "type": "skin",
        "name": "玫瑰午睡时",
        "nameEn": "Repose Amidst the Roses",
        "released": false
      }
    ],
    "defaultVariant": "312101"
  },
  {
    "id": "3120",
    "baseId": "3120",
    "names": {
      "zh-CN": "诺谛卡",
      "zh-TW": "諾諦卡",
      "en-US": "Nautika",
      "ja-JP": "ノーティカ",
      "ko-KR": "노티카"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 24,
    "released": true,
    "skins": [
      {
        "id": "312001",
        "type": "default",
        "released": true
      },
      {
        "id": "312002",
        "type": "insight",
        "name": "“未知”的背面",
        "nameEn": "Behind the \"Unknown\"",
        "released": true
      },
      {
        "id": "312003",
        "type": "skin",
        "name": "名以光辉",
        "nameEn": "From Darkness, Light",
        "released": true
      }
    ],
    "defaultVariant": "312001"
  },
  {
    "id": "3117",
    "baseId": "3117",
    "names": {
      "zh-CN": "库珀花环",
      "zh-TW": "庫珀花環",
      "en-US": "Kiperina",
      "ja-JP": "カイパリーナ",
      "ko-KR": "키페리나"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 25,
    "released": true,
    "skins": [
      {
        "id": "311701",
        "type": "default",
        "released": true
      },
      {
        "id": "311702",
        "type": "insight",
        "name": "弹珠匣",
        "nameEn": "A Box of Marbles",
        "released": true
      },
      {
        "id": "311703",
        "type": "skin",
        "name": "宇宙之壳",
        "nameEn": "The Universe in the Rook's Shell",
        "released": true
      },
      {
        "id": "311704",
        "type": "skin",
        "name": "玻璃乌托邦",
        "nameEn": "A Utopia in Painted Glass",
        "released": true
      }
    ],
    "defaultVariant": "311701"
  },
  {
    "id": "3116",
    "baseId": "3116",
    "names": {
      "zh-CN": "冷周六",
      "zh-TW": "冷週六",
      "en-US": "Hissabeth",
      "ja-JP": "サーベス",
      "ko-KR": "히사베스"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 26,
    "released": true,
    "skins": [
      {
        "id": "311601",
        "type": "default",
        "released": true
      },
      {
        "id": "311602",
        "type": "insight",
        "name": "电子丛林发展史",
        "nameEn": "Digital Jungle",
        "released": true
      },
      {
        "id": "311603",
        "type": "skin",
        "name": "群蛇的春祭",
        "nameEn": "Serpentine Primavera",
        "released": true
      },
      {
        "id": "311604",
        "type": "skin",
        "name": "巫阳抚彗歌",
        "nameEn": "Verses to Heaven",
        "released": false
      }
    ],
    "defaultVariant": "311601"
  },
  {
    "id": "3114",
    "baseId": "3114",
    "names": {
      "zh-CN": "虚构集",
      "zh-TW": "虛構集",
      "en-US": "Recoleta",
      "ja-JP": "レコレータ",
      "ko-KR": "레콜레타"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 27,
    "released": true,
    "skins": [
      {
        "id": "311401",
        "type": "default",
        "released": true
      },
      {
        "id": "311402",
        "type": "insight",
        "name": "卷首语",
        "nameEn": "Foreword",
        "released": true
      },
      {
        "id": "311403",
        "type": "skin",
        "name": "拉曼却幻想",
        "nameEn": "The Knight of La Mancha",
        "released": true
      },
      {
        "id": "311404",
        "type": "skin",
        "name": "文字，自始至终",
        "nameEn": "The Weight of Words",
        "released": true
      }
    ],
    "defaultVariant": "311401"
  },
  {
    "id": "3113",
    "baseId": "3113",
    "names": {
      "zh-CN": "阿莱夫",
      "zh-TW": "阿萊夫",
      "en-US": "Aleph",
      "ja-JP": "エル・アレフ",
      "ko-KR": "알레프"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 28,
    "released": true,
    "skins": [
      {
        "id": "311301",
        "type": "default",
        "released": true
      },
      {
        "id": "311302",
        "type": "insight",
        "name": "无限议题",
        "nameEn": "Infinitude",
        "released": true
      },
      {
        "id": "311303",
        "type": "skin",
        "name": "意象的欢宴",
        "nameEn": "A Feast of Imagery",
        "released": true
      }
    ],
    "defaultVariant": "311301"
  },
  {
    "id": "3111",
    "baseId": "3111",
    "names": {
      "zh-CN": "菲林士多",
      "zh-TW": "菲林士多",
      "en-US": "Noire",
      "ja-JP": "ノワール",
      "ko-KR": "누아르"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 29,
    "released": true,
    "skins": [
      {
        "id": "311101",
        "type": "default",
        "released": true
      },
      {
        "id": "311102",
        "type": "insight",
        "name": "红毯嘉宾",
        "nameEn": "On the Red Carpet",
        "released": true
      },
      {
        "id": "311103",
        "type": "skin",
        "name": "算尘寰",
        "nameEn": "The Trapped Trapmaster",
        "released": true
      }
    ],
    "defaultVariant": "311101"
  },
  {
    "id": "3110",
    "baseId": "3110",
    "names": {
      "zh-CN": "梁月",
      "zh-TW": "梁月",
      "en-US": "Liang Yue",
      "ja-JP": "梁月",
      "ko-KR": "양월"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 30,
    "released": true,
    "skins": [
      {
        "id": "311001",
        "type": "default",
        "released": true
      },
      {
        "id": "311002",
        "type": "insight",
        "name": "青瓦之上",
        "nameEn": "Above the Green Tiles",
        "released": true
      },
      {
        "id": "311003",
        "type": "skin",
        "name": "照雪明",
        "nameEn": "The Moon's Reflection",
        "released": true
      }
    ],
    "defaultVariant": "311001"
  },
  {
    "id": "3109",
    "baseId": "3109",
    "names": {
      "zh-CN": "图图石子",
      "zh-TW": "圖圖石子",
      "en-US": "Fatutu",
      "ja-JP": "トゥトゥイ",
      "ko-KR": "파투투"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 31,
    "released": true,
    "skins": [
      {
        "id": "310901",
        "type": "default",
        "released": true
      },
      {
        "id": "310902",
        "type": "insight",
        "name": "消逝的涟漪",
        "nameEn": "Fading Ripples",
        "released": true
      },
      {
        "id": "310903",
        "type": "skin",
        "name": "曲线的居所",
        "nameEn": "Casa of the Curved Lines",
        "released": true
      },
      {
        "id": "310905",
        "type": "skin",
        "name": "故梦罅隙间",
        "nameEn": "Fragments of An Old Dream",
        "released": true
      }
    ],
    "defaultVariant": "310901"
  },
  {
    "id": "3108",
    "baseId": "3108",
    "names": {
      "zh-CN": "芭卡洛儿",
      "zh-TW": "芭卡洛兒",
      "en-US": "Barcarola",
      "ja-JP": "バルカローラ",
      "ko-KR": "바르카롤라"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 32,
    "released": true,
    "skins": [
      {
        "id": "310801",
        "type": "default",
        "released": true
      },
      {
        "id": "310802",
        "type": "insight",
        "name": "海风领奏",
        "nameEn": "As the Sea Breeze Leads",
        "released": true
      },
      {
        "id": "310803",
        "type": "skin",
        "name": "飞越行星带",
        "nameEn": "Asteroid Allegro",
        "released": true
      }
    ],
    "defaultVariant": "310801"
  },
  {
    "id": "3107",
    "baseId": "3107",
    "names": {
      "zh-CN": "乌尔里希",
      "zh-TW": "烏爾里希",
      "en-US": "Ulrich",
      "ja-JP": "ウルリッヒ",
      "ko-KR": "울리히"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 33,
    "released": true,
    "skins": [
      {
        "id": "310701",
        "type": "default",
        "released": true
      },
      {
        "id": "310702",
        "type": "insight",
        "name": "缸中宇宙",
        "nameEn": "Universe in the Tank",
        "released": true
      },
      {
        "id": "310703",
        "type": "skin",
        "name": "叩响天宇一角",
        "nameEn": "A Glimpse of the Cosmos",
        "released": true
      }
    ],
    "defaultVariant": "310701"
  },
  {
    "id": "3105",
    "baseId": "3105",
    "names": {
      "zh-CN": "纸信圈儿",
      "zh-TW": "紙信圈兒",
      "en-US": "Flutterpage",
      "ja-JP": "パタパタペーパー",
      "ko-KR": "플러터 페이지"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 34,
    "released": true,
    "skins": [
      {
        "id": "310501",
        "type": "default",
        "released": true
      },
      {
        "id": "310502",
        "type": "insight",
        "name": "啁啾来访日",
        "nameEn": "Chirpy Morning Ringer",
        "released": true
      },
      {
        "id": "310503",
        "type": "skin",
        "name": "明日的春风",
        "nameEn": "Gently Comes the Thawing Breeze",
        "released": true
      },
      {
        "id": "310504",
        "type": "skin",
        "name": "原子时报晓",
        "nameEn": "Atomic Alarm",
        "released": true
      }
    ],
    "defaultVariant": "310501"
  },
  {
    "id": "3104",
    "baseId": "3104",
    "names": {
      "zh-CN": "笃笃骨",
      "zh-TW": "篤篤骨",
      "en-US": "Willow",
      "ja-JP": "ヴィロー",
      "ko-KR": "윌로우"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 35,
    "released": true,
    "skins": [
      {
        "id": "310401",
        "type": "default",
        "released": true
      },
      {
        "id": "310402",
        "type": "insight",
        "name": "旷然独舞",
        "nameEn": "Lone Dancer",
        "released": true
      },
      {
        "id": "310403",
        "type": "skin",
        "name": "第二枚预兆",
        "nameEn": "The Last Portent",
        "released": true
      },
      {
        "id": "310404",
        "type": "skin",
        "name": "裁春衫",
        "nameEn": "Reborn and Restored",
        "released": true
      }
    ],
    "defaultVariant": "310401"
  },
  {
    "id": "3102",
    "baseId": "3102",
    "names": {
      "zh-CN": "洛佩拉",
      "zh-TW": "洛佩拉",
      "en-US": "Lopera",
      "ja-JP": "ロペラ",
      "ko-KR": "로페라"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 36,
    "released": true,
    "skins": [
      {
        "id": "310201",
        "type": "default",
        "released": true
      },
      {
        "id": "310202",
        "type": "insight",
        "name": "落日归途",
        "nameEn": "The Wayward Soul Returns",
        "released": true
      },
      {
        "id": "310203",
        "type": "skin",
        "name": "与风暴同行",
        "nameEn": "Friend of the Splintercat",
        "released": true
      }
    ],
    "defaultVariant": "310201"
  },
  {
    "id": "3100",
    "baseId": "3100",
    "names": {
      "zh-CN": "天使娜娜",
      "zh-TW": "天使娜娜",
      "en-US": "Anjo Nala",
      "ja-JP": "アンジョナナ",
      "ko-KR": "안조 날라"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 37,
    "released": true,
    "skins": [
      {
        "id": "310001",
        "type": "default",
        "released": true
      },
      {
        "id": "310002",
        "type": "insight",
        "name": "无忧年代",
        "nameEn": "Carefree Days",
        "released": true
      },
      {
        "id": "310003",
        "type": "skin",
        "name": "恶之果",
        "nameEn": "Forbidden Fruit",
        "released": true
      }
    ],
    "defaultVariant": "310001"
  },
  {
    "id": "3098",
    "baseId": "3098",
    "names": {
      "zh-CN": "蓝手帕",
      "zh-TW": "藍手帕",
      "en-US": "Tuesday",
      "ja-JP": "チューズデー",
      "ko-KR": "튜즈데이"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 38,
    "released": true,
    "skins": [
      {
        "id": "309801",
        "type": "default",
        "released": true
      },
      {
        "id": "309802",
        "type": "insight",
        "name": "恐惧女主人",
        "nameEn": "Miss Horror",
        "released": true
      },
      {
        "id": "309803",
        "type": "skin",
        "name": "玉瓶宝鉴",
        "nameEn": "Story of the Jade Vase",
        "released": true
      },
      {
        "id": "309804",
        "type": "skin",
        "name": "冷襁褓",
        "nameEn": "Cold Cradle",
        "released": true
      }
    ],
    "defaultVariant": "309801"
  },
  {
    "id": "3097",
    "baseId": "3097",
    "names": {
      "zh-CN": "阿尔古斯",
      "zh-TW": "阿爾古斯",
      "en-US": "Argus",
      "ja-JP": "アルゴス",
      "ko-KR": "아르고스"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 39,
    "released": true,
    "skins": [
      {
        "id": "309701",
        "type": "default",
        "released": true
      },
      {
        "id": "309702",
        "type": "insight",
        "name": "百眼燃烧",
        "nameEn": "All Seeing Light",
        "released": true
      },
      {
        "id": "309703",
        "type": "skin",
        "name": "星间追猎秀",
        "nameEn": "Starbound Bounty Hunter",
        "released": true
      }
    ],
    "defaultVariant": "309701"
  },
  {
    "id": "3095",
    "baseId": "3095",
    "names": {
      "zh-CN": "环状水星",
      "zh-TW": "環狀水星",
      "en-US": "Mercuria",
      "ja-JP": "マーキュリア",
      "ko-KR": "머큐리아"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 40,
    "released": true,
    "skins": [
      {
        "id": "309501",
        "type": "default",
        "released": true
      },
      {
        "id": "309502",
        "type": "insight",
        "name": "宇宙屏息时",
        "nameEn": "The Universe Holds Its Breath",
        "released": true
      },
      {
        "id": "309503",
        "type": "skin",
        "name": "午夜曼波",
        "nameEn": "Midnight Mistmancer",
        "released": true
      },
      {
        "id": "309504",
        "type": "skin",
        "name": "惊魂夜颂歌",
        "nameEn": "The Nightmare's Carol",
        "released": true
      }
    ],
    "defaultVariant": "309501"
  },
  {
    "id": "3094",
    "baseId": "3094",
    "names": {
      "zh-CN": "J",
      "zh-TW": "J",
      "en-US": "J",
      "ja-JP": "J",
      "ko-KR": "J"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 41,
    "released": true,
    "skins": [
      {
        "id": "309401",
        "type": "default",
        "released": true
      },
      {
        "id": "309402",
        "type": "insight",
        "name": "极速前线",
        "nameEn": "Top Speed Rider",
        "released": true
      },
      {
        "id": "309403",
        "type": "skin",
        "name": "野嗥",
        "nameEn": "The Lone Wolf's Howl",
        "released": true
      }
    ],
    "defaultVariant": "309401"
  },
  {
    "id": "3092",
    "baseId": "3092",
    "names": {
      "zh-CN": "伊戈尔",
      "zh-TW": "伊戈爾",
      "en-US": "Igor",
      "ja-JP": "イゴール",
      "ko-KR": "이고르"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 42,
    "released": true,
    "skins": [
      {
        "id": "309201",
        "type": "default",
        "released": true
      },
      {
        "id": "309202",
        "type": "insight",
        "name": "旗帜所指向的",
        "nameEn": "Where the Banner Points",
        "released": true
      },
      {
        "id": "309203",
        "type": "skin",
        "name": "幽冥无归",
        "nameEn": "Returning Nevermore",
        "released": false
      }
    ],
    "defaultVariant": "309201"
  },
  {
    "id": "3088",
    "baseId": "3088",
    "names": {
      "zh-CN": "塞梅尔维斯",
      "zh-TW": "塞梅爾維斯",
      "en-US": "Semmelweis",
      "ja-JP": "センメルワイス",
      "ko-KR": "제멜바이스"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 43,
    "released": true,
    "skins": [
      {
        "id": "308801",
        "type": "default",
        "released": true
      },
      {
        "id": "308802",
        "type": "insight",
        "name": "镜",
        "nameEn": "The Mirror",
        "released": true
      },
      {
        "id": "308803",
        "type": "skin",
        "name": "叩门礼仪",
        "nameEn": "A Knock on the Door",
        "released": true
      },
      {
        "id": "308804",
        "type": "skin",
        "name": "心之盈亏",
        "nameEn": "The Wax and Wane of the Heart",
        "released": true
      }
    ],
    "defaultVariant": "308801"
  },
  {
    "id": "3087",
    "baseId": "3087",
    "names": {
      "zh-CN": "维拉",
      "zh-TW": "維拉",
      "en-US": "Vila",
      "ja-JP": "ヴィラ",
      "ko-KR": "빌라"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 44,
    "released": true,
    "skins": [
      {
        "id": "308701",
        "type": "default",
        "released": true
      },
      {
        "id": "308702",
        "type": "insight",
        "name": "向理想，向生活",
        "nameEn": "Towards the Ideal Life",
        "released": true
      },
      {
        "id": "308703",
        "type": "skin",
        "name": "远眺色彩",
        "nameEn": "By the Painted City",
        "released": true
      },
      {
        "id": "308704",
        "type": "skin",
        "name": "酒色之海的女儿",
        "nameEn": "Daughter of the Wine-Dark Sea",
        "released": true
      }
    ],
    "defaultVariant": "308701"
  },
  {
    "id": "3086",
    "baseId": "3086",
    "names": {
      "zh-CN": "露西",
      "zh-TW": "露西",
      "en-US": "Lucy",
      "ja-JP": "ルーシー",
      "ko-KR": "루시"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 45,
    "released": true,
    "skins": [
      {
        "id": "308601",
        "type": "default",
        "released": true
      },
      {
        "id": "308602",
        "type": "insight",
        "name": "一个机器人的诞生",
        "nameEn": "A Robot Is Born",
        "released": true
      },
      {
        "id": "308603",
        "type": "skin",
        "name": "生如行棋",
        "nameEn": "The Queen's Game",
        "released": true
      }
    ],
    "defaultVariant": "308601"
  },
  {
    "id": "3084",
    "baseId": "3084",
    "names": {
      "zh-CN": "葛天",
      "zh-TW": "葛天",
      "en-US": "Getian",
      "ja-JP": "葛天",
      "ko-KR": "갈천"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 46,
    "released": true,
    "skins": [
      {
        "id": "308401",
        "type": "default",
        "released": true
      },
      {
        "id": "308402",
        "type": "insight",
        "name": "清风吹我襟",
        "nameEn": "The Breeze of Ease",
        "released": true
      },
      {
        "id": "308404",
        "type": "skin",
        "name": "入埃及记",
        "nameEn": "Herald of Horus",
        "released": true
      }
    ],
    "defaultVariant": "308401"
  },
  {
    "id": "3083",
    "baseId": "3083",
    "names": {
      "zh-CN": "曲娘",
      "zh-TW": "曲娘",
      "en-US": "Jiu Niangzi",
      "ja-JP": "曲娘",
      "ko-KR": "곡랑"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 47,
    "released": true,
    "skins": [
      {
        "id": "308301",
        "type": "default",
        "released": true
      },
      {
        "id": "308302",
        "type": "insight",
        "name": "天光照衣",
        "nameEn": "Let There Be Way Out",
        "released": true
      },
      {
        "id": "308303",
        "type": "skin",
        "name": "壁上桃源",
        "nameEn": "Blossom Spring Fairy",
        "released": true
      }
    ],
    "defaultVariant": "308301"
  },
  {
    "id": "3081",
    "baseId": "3081",
    "names": {
      "zh-CN": "伊索尔德",
      "zh-TW": "伊索爾德",
      "en-US": "Isolde",
      "ja-JP": "イゾルデ",
      "ko-KR": "이졸데"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 48,
    "released": true,
    "skins": [
      {
        "id": "308101",
        "type": "default",
        "released": true
      },
      {
        "id": "308102",
        "type": "insight",
        "name": "多重唱",
        "nameEn": "Polyphony",
        "released": true
      },
      {
        "id": "308103",
        "type": "skin",
        "name": "爵士春秋",
        "nameEn": "And All That Jazz",
        "released": true
      },
      {
        "id": "308104",
        "type": "skin",
        "name": "若向死振翅",
        "nameEn": "The Last Fluttering Beat",
        "released": true
      }
    ],
    "defaultVariant": "308101"
  },
  {
    "id": "3080",
    "baseId": "3080",
    "names": {
      "zh-CN": "卡卡尼亚",
      "zh-TW": "卡卡尼亞",
      "en-US": "Kakania",
      "ja-JP": "カカニア",
      "ko-KR": "카카니아"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 49,
    "released": true,
    "skins": [
      {
        "id": "308001",
        "type": "default",
        "released": true
      },
      {
        "id": "308002",
        "type": "insight",
        "name": "映像之映像",
        "nameEn": "Reflections within Reflections",
        "released": true
      },
      {
        "id": "308003",
        "type": "skin",
        "name": "心曲沙龙",
        "nameEn": "Seminars on Serenity",
        "released": true
      },
      {
        "id": "308004",
        "type": "skin",
        "name": "时代病陪护",
        "nameEn": "Guardian of the Broken",
        "released": true
      }
    ],
    "defaultVariant": "308001"
  },
  {
    "id": "3079",
    "baseId": "3079",
    "names": {
      "zh-CN": "6",
      "zh-TW": "6",
      "en-US": "6",
      "ja-JP": "6",
      "ko-KR": "6"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 50,
    "released": true,
    "skins": [
      {
        "id": "307901",
        "type": "default",
        "released": true
      },
      {
        "id": "307902",
        "type": "insight",
        "name": "完备者",
        "nameEn": "The Perfect Number",
        "released": true
      },
      {
        "id": "307903",
        "type": "skin",
        "name": "何时何地",
        "nameEn": "Time and Location",
        "released": true
      },
      {
        "id": "307904",
        "type": "skin",
        "name": "于火中得见",
        "nameEn": "By the Razed Polis",
        "released": true
      },
      {
        "id": "307905",
        "type": "skin",
        "name": "孤独赞美诗",
        "nameEn": "A Hymn to Seclusion",
        "released": true
      }
    ],
    "defaultVariant": "307901"
  },
  {
    "id": "3077",
    "baseId": "3077",
    "names": {
      "zh-CN": "北方哨歌",
      "zh-TW": "北方哨歌",
      "en-US": "Windsong",
      "ja-JP": "スヴィスティ",
      "ko-KR": "윈드송"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 51,
    "released": true,
    "skins": [
      {
        "id": "307701",
        "type": "default",
        "released": true
      },
      {
        "id": "307702",
        "type": "insight",
        "name": "于此丈量",
        "nameEn": "Measuring the World",
        "released": true
      },
      {
        "id": "307703",
        "type": "skin",
        "name": "凿玉记",
        "nameEn": "Records from the Jade Hunt",
        "released": true
      },
      {
        "id": "307704",
        "type": "skin",
        "name": "魇与夜",
        "nameEn": "The Nightmare's Trespasser",
        "released": true
      },
      {
        "id": "307705",
        "type": "skin",
        "name": "银色等高线",
        "nameEn": "Silver Isoheight",
        "released": true
      }
    ],
    "defaultVariant": "307701"
  },
  {
    "id": "3074",
    "baseId": "3074",
    "names": {
      "zh-CN": "爱兹拉",
      "zh-TW": "愛茲拉",
      "en-US": "Ezra",
      "ja-JP": "エズラ",
      "ko-KR": "에즈라"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 52,
    "released": true,
    "skins": [
      {
        "id": "307401",
        "type": "default",
        "released": true
      },
      {
        "id": "307402",
        "type": "insight",
        "name": "菌伞的启示",
        "nameEn": "Enlightened by Mushrooms",
        "released": true
      },
      {
        "id": "307403",
        "type": "skin",
        "name": "噫～嗬！",
        "nameEn": "Yee-Haw!",
        "released": true
      }
    ],
    "defaultVariant": "307401"
  },
  {
    "id": "3073",
    "baseId": "3073",
    "names": {
      "zh-CN": "可燃点",
      "zh-TW": "可燃點",
      "en-US": "Spathodea",
      "ja-JP": "カエンボク",
      "ko-KR": "스파토데아"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 53,
    "released": true,
    "skins": [
      {
        "id": "307301",
        "type": "default",
        "released": true
      },
      {
        "id": "307302",
        "type": "insight",
        "name": "雀儿、火焰、花",
        "nameEn": "Sparrow, Hummingbird, Flower",
        "released": true
      },
      {
        "id": "307303",
        "type": "skin",
        "name": "胜利冲刺",
        "nameEn": "Onwards, To Victory!",
        "released": true
      },
      {
        "id": "307304",
        "type": "skin",
        "name": "火芙蕖",
        "nameEn": "Fire Lotus",
        "released": true
      }
    ],
    "defaultVariant": "307301"
  },
  {
    "id": "3072",
    "baseId": "3072",
    "names": {
      "zh-CN": "鬃毛沙砾",
      "zh-TW": "鬃毛沙礫",
      "en-US": "Shamane",
      "ja-JP": "シャーマィン",
      "ko-KR": "갈기 모래"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 54,
    "released": true,
    "skins": [
      {
        "id": "307201",
        "type": "default",
        "released": true
      },
      {
        "id": "307202",
        "type": "insight",
        "name": "山麓以南",
        "nameEn": "South of the Mountain",
        "released": true
      },
      {
        "id": "307203",
        "type": "skin",
        "name": "玛瑙斯印迹",
        "nameEn": "Beneath the Jungle Canopy",
        "released": true
      }
    ],
    "defaultVariant": "307201"
  },
  {
    "id": "3070",
    "baseId": "3070",
    "names": {
      "zh-CN": "伽菈波那",
      "zh-TW": "伽菈波那",
      "en-US": "Kaalaa Baunaa",
      "ja-JP": "カーラ・ボナー",
      "ko-KR": "갈라보나"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 55,
    "released": true,
    "skins": [
      {
        "id": "307001",
        "type": "default",
        "released": true
      },
      {
        "id": "307002",
        "type": "insight",
        "name": "仰望者",
        "nameEn": "The Star Reader",
        "released": true
      },
      {
        "id": "307003",
        "type": "skin",
        "name": "勾手，起跳，悬停",
        "nameEn": "Swing, Rise, Suspend",
        "released": true
      },
      {
        "id": "307004",
        "type": "skin",
        "name": "太阳何时瞑目",
        "nameEn": "Till the Sun Falls",
        "released": true
      }
    ],
    "defaultVariant": "307001"
  },
  {
    "id": "3066",
    "baseId": "3066",
    "names": {
      "zh-CN": "37",
      "zh-TW": "37",
      "en-US": "37",
      "ja-JP": "37",
      "ko-KR": "37"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 56,
    "released": true,
    "skins": [
      {
        "id": "306601",
        "type": "default",
        "released": true
      },
      {
        "id": "306602",
        "type": "insight",
        "name": "一位质数",
        "nameEn": "A Prime Number",
        "released": true
      },
      {
        "id": "306603",
        "type": "skin",
        "name": "快乐的捕鸟人",
        "nameEn": "Happy Bird Catcher",
        "released": true
      },
      {
        "id": "306604",
        "type": "skin",
        "name": "泉眼深处",
        "nameEn": "Down in the Grotto",
        "released": true
      },
      {
        "id": "306605",
        "type": "skin",
        "name": "完美的流体",
        "nameEn": "A Gift of Nourishment",
        "released": true
      }
    ],
    "defaultVariant": "306601"
  },
  {
    "id": "3065",
    "baseId": "3065",
    "names": {
      "zh-CN": "马库斯",
      "zh-TW": "馬庫斯",
      "en-US": "Marcus",
      "ja-JP": "マーカス",
      "ko-KR": "마커스"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 57,
    "released": true,
    "skins": [
      {
        "id": "306501",
        "type": "default",
        "released": true
      },
      {
        "id": "306502",
        "type": "insight",
        "name": "风儿吹回那日",
        "nameEn": "A Returning Wind",
        "released": true
      },
      {
        "id": "306503",
        "type": "skin",
        "name": "白沙与风",
        "nameEn": "On the White Sand",
        "released": true
      },
      {
        "id": "306504",
        "type": "skin",
        "name": "致冥府的门扉",
        "nameEn": "To the Gates of the Underworld",
        "released": true
      }
    ],
    "defaultVariant": "306501"
  },
  {
    "id": "3063",
    "baseId": "3063",
    "names": {
      "zh-CN": "皮克勒斯",
      "zh-TW": "皮克勒斯",
      "en-US": "Pickles",
      "ja-JP": "ピクルス",
      "ko-KR": "피클즈"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 58,
    "released": true,
    "skins": [
      {
        "id": "306301",
        "type": "default",
        "released": true
      },
      {
        "id": "306302",
        "type": "insight",
        "name": "靛色毛茸茸",
        "nameEn": "An Indigo Fluff",
        "released": true
      },
      {
        "id": "306303",
        "type": "skin",
        "name": "狗狗与海",
        "nameEn": "The Young Dog and The Sea",
        "released": true
      }
    ],
    "defaultVariant": "306301"
  },
  {
    "id": "3062",
    "baseId": "3062",
    "names": {
      "zh-CN": "梅兰妮",
      "zh-TW": "梅蘭妮",
      "en-US": "Melania",
      "ja-JP": "メラニア",
      "ko-KR": "멜라니아"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 59,
    "released": true,
    "skins": [
      {
        "id": "306201",
        "type": "default",
        "released": true
      },
      {
        "id": "306202",
        "type": "insight",
        "name": "拉米雷斯风格",
        "nameEn": "The Ramirez Style",
        "released": true
      },
      {
        "id": "306203",
        "type": "skin",
        "name": "夜晚如此祥和",
        "nameEn": "A Peaceful Night",
        "released": true
      },
      {
        "id": "306204",
        "type": "skin",
        "name": "红与白",
        "nameEn": "Red and White",
        "released": true
      }
    ],
    "defaultVariant": "306201"
  },
  {
    "id": "3056",
    "baseId": "3056",
    "names": {
      "zh-CN": "洁西卡",
      "zh-TW": "潔西卡",
      "en-US": "Jessica",
      "ja-JP": "ジェシカ",
      "ko-KR": "제시카"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 60,
    "released": true,
    "skins": [
      {
        "id": "305601",
        "type": "default",
        "released": true
      },
      {
        "id": "305602",
        "type": "insight",
        "name": "捉迷藏",
        "nameEn": "Hide and Seek",
        "released": true
      },
      {
        "id": "305603",
        "type": "skin",
        "name": "午后曳航",
        "nameEn": "Voyage from your Bed",
        "released": true
      },
      {
        "id": "305604",
        "type": "skin",
        "name": "乐园之声",
        "nameEn": "The Sound of Paradise",
        "released": true
      }
    ],
    "defaultVariant": "305601"
  },
  {
    "id": "3053",
    "baseId": "3053",
    "names": {
      "zh-CN": "牙仙",
      "zh-TW": "牙仙",
      "en-US": "Tooth Fairy",
      "ja-JP": "トゥースフェアリー",
      "ko-KR": "투스 페어리"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 61,
    "released": true,
    "skins": [
      {
        "id": "305301",
        "type": "default",
        "released": true
      },
      {
        "id": "305302",
        "type": "insight",
        "name": "“甜美的梦”",
        "nameEn": "Sweet Dream",
        "released": true
      },
      {
        "id": "305303",
        "type": "skin",
        "name": "贝果核",
        "nameEn": "Bagel",
        "released": true
      },
      {
        "id": "305304",
        "type": "skin",
        "name": "妖精蹈足于晨",
        "nameEn": "Fairies Dancing at Dawn",
        "released": true
      },
      {
        "id": "305305",
        "type": "skin",
        "name": "彩衣曲",
        "nameEn": "The Woven Legend",
        "released": true
      }
    ],
    "defaultVariant": "305301"
  },
  {
    "id": "3052",
    "baseId": "3052",
    "names": {
      "zh-CN": "新巴别塔",
      "zh-TW": "新巴別塔",
      "en-US": "Ms. NewBabel",
      "ja-JP": "ニューバベル",
      "ko-KR": "뉴바벨"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 62,
    "released": true,
    "skins": [
      {
        "id": "305201",
        "type": "default",
        "released": true
      },
      {
        "id": "305202",
        "type": "insight",
        "name": "时代的缔造者",
        "nameEn": "Creator of the New Era",
        "released": true
      },
      {
        "id": "305203",
        "type": "skin",
        "name": "以善意加码",
        "nameEn": "Raise the Bid",
        "released": true
      }
    ],
    "defaultVariant": "305201"
  },
  {
    "id": "3051",
    "baseId": "3051",
    "names": {
      "zh-CN": "温妮弗雷德",
      "zh-TW": "溫妮弗雷德",
      "en-US": "Eternity",
      "ja-JP": "エターニティ",
      "ko-KR": "이터니티"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 63,
    "released": true,
    "skins": [
      {
        "id": "305101",
        "type": "default",
        "released": true
      },
      {
        "id": "305102",
        "type": "insight",
        "name": "永夜的淑女",
        "nameEn": "Lady of the Evernight",
        "released": true
      },
      {
        "id": "305103",
        "type": "skin",
        "name": "极地远望",
        "nameEn": "A Visit to the Arctic",
        "released": true
      },
      {
        "id": "305104",
        "type": "skin",
        "name": "以黄金哺育",
        "nameEn": "The Golden Nurturer",
        "released": true
      }
    ],
    "defaultVariant": "305101"
  },
  {
    "id": "3048",
    "baseId": "3048",
    "names": {
      "zh-CN": "远旅",
      "zh-TW": "遠旅",
      "en-US": "Voyager",
      "ja-JP": "ボイジャー",
      "ko-KR": "보이저"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 64,
    "released": true,
    "skins": [
      {
        "id": "304801",
        "type": "default",
        "released": true
      },
      {
        "id": "304802",
        "type": "insight",
        "name": "少言的信",
        "nameEn": "A Wordless Letter",
        "released": true
      },
      {
        "id": "304803",
        "type": "skin",
        "name": "再一次上路",
        "nameEn": "New Journey",
        "released": true
      },
      {
        "id": "304804",
        "type": "skin",
        "name": "群星齐唱时",
        "nameEn": "Choir of the Stars",
        "released": true
      }
    ],
    "defaultVariant": "304801"
  },
  {
    "id": "3047",
    "baseId": "3047",
    "names": {
      "zh-CN": "兔毛手袋",
      "zh-TW": "兔毛手袋",
      "en-US": "Medicine Pocket",
      "ja-JP": "メディスンポケット",
      "ko-KR": "메디슨 포켓"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 65,
    "released": true,
    "skins": [
      {
        "id": "304701",
        "type": "default",
        "released": true
      },
      {
        "id": "304702",
        "type": "insight",
        "name": "内有恶犬",
        "nameEn": "Beware of Dog",
        "released": true
      },
      {
        "id": "304703",
        "type": "skin",
        "name": "宇宙写真者",
        "nameEn": "The Cosmos Photographer ",
        "released": true
      },
      {
        "id": "304704",
        "type": "skin",
        "name": "永生苦短",
        "nameEn": "Forever Is Too Short",
        "released": true
      }
    ],
    "defaultVariant": "304701"
  },
  {
    "id": "3039",
    "baseId": "3039",
    "names": {
      "zh-CN": "泥鯭的士",
      "zh-TW": "泥鯭的士",
      "en-US": "An-an Lee",
      "ja-JP": "リー・アンアン",
      "ko-KR": "안안 리"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 66,
    "released": true,
    "skins": [
      {
        "id": "303901",
        "type": "default",
        "released": true
      },
      {
        "id": "303902",
        "type": "insight",
        "name": "HK鬼见愁",
        "nameEn": "Ghost Predator of HK",
        "released": true
      },
      {
        "id": "303903",
        "type": "skin",
        "name": "松云之间",
        "nameEn": "Between Clouds and Pine Trees",
        "released": true
      },
      {
        "id": "303904",
        "type": "skin",
        "name": "共生花",
        "nameEn": "Symbiotic Lee-ly",
        "released": true
      }
    ],
    "defaultVariant": "303901"
  },
  {
    "id": "3032",
    "baseId": "3032",
    "names": {
      "zh-CN": "百夫长",
      "zh-TW": "百夫長",
      "en-US": "Centurion",
      "ja-JP": "ケントゥリオン",
      "ko-KR": "센츄리온"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 67,
    "released": true,
    "skins": [
      {
        "id": "303201",
        "type": "default",
        "released": true
      },
      {
        "id": "303202",
        "type": "insight",
        "name": "伟大秀场",
        "nameEn": "The Great Show",
        "released": true
      },
      {
        "id": "303203",
        "type": "skin",
        "name": "环球之星",
        "nameEn": "The Universal Star",
        "released": true
      }
    ],
    "defaultVariant": "303201"
  },
  {
    "id": "3025",
    "baseId": "3025",
    "names": {
      "zh-CN": "星锑",
      "zh-TW": "星銻",
      "en-US": "Regulus",
      "ja-JP": "レグルス",
      "ko-KR": "레굴루스"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 68,
    "released": true,
    "skins": [
      {
        "id": "302501",
        "type": "default",
        "released": true
      },
      {
        "id": "302502",
        "type": "insight",
        "name": "灼热闪耀之星",
        "nameEn": "A Flaring Star",
        "released": true
      },
      {
        "id": "302503",
        "type": "skin",
        "name": "狂热分子",
        "nameEn": "The Fierce Fan",
        "released": true
      },
      {
        "id": "302504",
        "type": "skin",
        "name": "启航！向明日",
        "nameEn": "Take Off! To the Future",
        "released": true
      }
    ],
    "defaultVariant": "302501"
  },
  {
    "id": "3009",
    "baseId": "3009",
    "names": {
      "zh-CN": "苏芙比",
      "zh-TW": "蘇芙比",
      "en-US": "Sotheby",
      "ja-JP": "サザビー",
      "ko-KR": "소더비"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 69,
    "released": true,
    "skins": [
      {
        "id": "300901",
        "type": "default",
        "released": true
      },
      {
        "id": "300902",
        "type": "insight",
        "name": "另一侧的世界",
        "nameEn": "World on the Other Side",
        "released": true
      },
      {
        "id": "300903",
        "type": "skin",
        "name": "帷幔深处",
        "nameEn": "Suspiriorum",
        "released": true
      },
      {
        "id": "300904",
        "type": "skin",
        "name": "红线缘",
        "nameEn": "The Red Thread of Fate",
        "released": true
      }
    ],
    "defaultVariant": "300901"
  },
  {
    "id": "3007",
    "baseId": "3007",
    "names": {
      "zh-CN": "未锈铠",
      "zh-TW": "未鏽鎧",
      "en-US": "A Knight",
      "ja-JP": "ナイト",
      "ko-KR": "A 나이트"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 70,
    "released": true,
    "skins": [
      {
        "id": "300701",
        "type": "default",
        "released": true
      },
      {
        "id": "300702",
        "type": "insight",
        "name": "加百列圣勋",
        "nameEn": "Order of St. Gabriel",
        "released": true
      },
      {
        "id": "300703",
        "type": "skin",
        "name": "策马行山河",
        "nameEn": "Galloping Across the Times",
        "released": true
      },
      {
        "id": "300731",
        "type": "skin",
        "name": "魂灵长青",
        "nameEn": "The Evergreen Soul",
        "released": true
      }
    ],
    "defaultVariant": "300701"
  },
  {
    "id": "3004",
    "baseId": "3004",
    "names": {
      "zh-CN": "红弩箭",
      "zh-TW": "紅弩箭",
      "en-US": "Lilya",
      "ja-JP": "リーリャ",
      "ko-KR": "릴리아"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 71,
    "released": true,
    "skins": [
      {
        "id": "300401",
        "type": "default",
        "released": true
      },
      {
        "id": "300402",
        "type": "insight",
        "name": "巴伦支海女巫",
        "nameEn": "The Barents Witch",
        "released": true
      },
      {
        "id": "300403",
        "type": "skin",
        "name": "几何技艺",
        "nameEn": "The Art of Destreza",
        "released": true
      },
      {
        "id": "300404",
        "type": "skin",
        "name": "永不迟到的公正",
        "nameEn": "Justice Cannot Be Delayed",
        "released": true
      }
    ],
    "defaultVariant": "300401"
  },
  {
    "id": "3003",
    "baseId": "3003",
    "names": {
      "zh-CN": "槲寄生",
      "zh-TW": "槲寄生",
      "en-US": "Druvis III",
      "ja-JP": "ドルーヴィスⅢ",
      "ko-KR": "드루비스"
    },
    "rarity": 5,
    "maxInsight": 3,
    "releaseOrder": 72,
    "released": true,
    "skins": [
      {
        "id": "300301",
        "type": "default",
        "released": true
      },
      {
        "id": "300302",
        "type": "insight",
        "name": "熟识橡树之人",
        "nameEn": "The Druid",
        "released": true
      },
      {
        "id": "300305",
        "type": "skin",
        "name": "闹蛾儿",
        "nameEn": "Lady With Nao'E",
        "released": true
      },
      {
        "id": "300306",
        "type": "skin",
        "name": "荆棘环绕处",
        "nameEn": "Shrouded in Thorns",
        "released": true
      }
    ],
    "defaultVariant": "300301"
  },
  {
    "id": "3154",
    "baseId": "3154",
    "names": {
      "zh-CN": "银装小春雀儿",
      "zh-TW": "銀裝小春雀兒",
      "en-US": "Silverwing Eagle",
      "ja-JP": "イーグル",
      "ko-KR": "은빛 이글"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 73,
    "released": true,
    "skins": [
      {
        "id": "315401",
        "type": "default",
        "released": true
      },
      {
        "id": "315402",
        "type": "insight",
        "name": "科学地成为科学家",
        "nameEn": "Becoming a Scientist, Scientifically",
        "released": true
      }
    ],
    "defaultVariant": "315401"
  },
  {
    "id": "3122",
    "baseId": "3122",
    "names": {
      "zh-CN": "阿利克西欧斯",
      "zh-TW": "亞歷克西歐斯",
      "en-US": "Alexios",
      "ja-JP": "アレクシオス",
      "ko-KR": "알렉시오스"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 74,
    "released": true,
    "skins": [
      {
        "id": "312201",
        "type": "default",
        "released": true
      },
      {
        "id": "312202",
        "type": "insight",
        "name": "第二次征服",
        "nameEn": "Second Conquest",
        "released": true
      }
    ],
    "defaultVariant": "312201"
  },
  {
    "id": "3118",
    "baseId": "3118",
    "names": {
      "zh-CN": "命名日",
      "zh-TW": "命名日",
      "en-US": "Name Day",
      "ja-JP": "ネイムデー",
      "ko-KR": "네임데이"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 75,
    "released": true,
    "skins": [
      {
        "id": "311801",
        "type": "default",
        "released": true
      },
      {
        "id": "311802",
        "type": "insight",
        "name": "趁光线消融前",
        "nameEn": "Before the Light Fades",
        "released": true
      },
      {
        "id": "311803",
        "type": "skin",
        "name": "永恒的沉默",
        "nameEn": "The Deathless Quiet",
        "released": true
      }
    ],
    "defaultVariant": "311801"
  },
  {
    "id": "3115",
    "baseId": "3115",
    "names": {
      "zh-CN": "嚼嚼松果",
      "zh-TW": "嚼嚼松果",
      "en-US": "Buddy Fairchild",
      "ja-JP": "もぐナッツ",
      "ko-KR": "버디 페어차일드"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 76,
    "released": true,
    "skins": [
      {
        "id": "311501",
        "type": "default",
        "released": true
      },
      {
        "id": "311502",
        "type": "insight",
        "name": "友情加冕",
        "nameEn": "A Ceremony Among Friends",
        "released": true
      }
    ],
    "defaultVariant": "311501"
  },
  {
    "id": "3112",
    "baseId": "3112",
    "names": {
      "zh-CN": "空脑袋",
      "zh-TW": "空腦袋",
      "en-US": "Loggerhead",
      "ja-JP": "ロガーヘッド",
      "ko-KR": "로거헤드"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 77,
    "released": true,
    "skins": [
      {
        "id": "311201",
        "type": "default",
        "released": true
      },
      {
        "id": "311202",
        "type": "insight",
        "name": "偷闲日",
        "nameEn": "A Moment of Leisure",
        "released": true
      }
    ],
    "defaultVariant": "311201"
  },
  {
    "id": "3106",
    "baseId": "3106",
    "names": {
      "zh-CN": "宽檐帽",
      "zh-TW": "寬簷帽",
      "en-US": "Brimley",
      "ja-JP": "つば広ハット",
      "ko-KR": "슬라우치 햇"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 78,
    "released": true,
    "skins": [
      {
        "id": "310601",
        "type": "default",
        "released": true
      },
      {
        "id": "310602",
        "type": "insight",
        "name": "午后密密缝",
        "nameEn": "Sunset Sartor",
        "released": true
      },
      {
        "id": "310604",
        "type": "skin",
        "name": "思维驾驶者",
        "nameEn": "THOUGHT Ranger",
        "released": true
      }
    ],
    "defaultVariant": "310601"
  },
  {
    "id": "3103",
    "baseId": "3103",
    "names": {
      "zh-CN": "邓肯先生",
      "zh-TW": "鄧肯先生",
      "en-US": "Mr. Duncan",
      "ja-JP": "ダンカン",
      "ko-KR": "던컨"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 79,
    "released": true,
    "skins": [
      {
        "id": "310301",
        "type": "default",
        "released": true
      },
      {
        "id": "310302",
        "type": "insight",
        "name": "巷尾发明家",
        "nameEn": "The Favela Inventor",
        "released": true
      }
    ],
    "defaultVariant": "310301"
  },
  {
    "id": "3099",
    "baseId": "3099",
    "names": {
      "zh-CN": "数羊羔",
      "zh-TW": "數羊羔",
      "en-US": "Barbara",
      "ja-JP": "メェプル",
      "ko-KR": "바바라"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 80,
    "released": true,
    "skins": [
      {
        "id": "309901",
        "type": "default",
        "released": true
      },
      {
        "id": "309902",
        "type": "insight",
        "name": "梦中青草地",
        "nameEn": "A Meadow in Her Dreams",
        "released": true
      }
    ],
    "defaultVariant": "309901"
  },
  {
    "id": "3091",
    "baseId": "3091",
    "names": {
      "zh-CN": "罗蕾莱",
      "zh-TW": "羅蕾萊",
      "en-US": "Lorelei",
      "ja-JP": "ローレライ",
      "ko-KR": "로렐라이"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 81,
    "released": true,
    "skins": [
      {
        "id": "309101",
        "type": "default",
        "released": true
      },
      {
        "id": "309102",
        "type": "insight",
        "name": "应祝祷之时",
        "nameEn": "Time to Pray",
        "released": true
      }
    ],
    "defaultVariant": "309101"
  },
  {
    "id": "3082",
    "baseId": "3082",
    "names": {
      "zh-CN": "小叶尼塞",
      "zh-TW": "小葉尼塞",
      "en-US": "Yenisei",
      "ja-JP": "エニセイ",
      "ko-KR": "예니세이"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 82,
    "released": true,
    "skins": [
      {
        "id": "308201",
        "type": "default",
        "released": true
      },
      {
        "id": "308202",
        "type": "insight",
        "name": "在同一条河中",
        "nameEn": "In the Same River",
        "released": true
      },
      {
        "id": "308203",
        "type": "skin",
        "name": "蓝河湾",
        "nameEn": "Around the Riverbend",
        "released": true
      }
    ],
    "defaultVariant": "308201"
  },
  {
    "id": "3078",
    "baseId": "3078",
    "names": {
      "zh-CN": "阿夫西维",
      "zh-TW": "阿夫西維",
      "en-US": "Avgust",
      "ja-JP": "アヴグスト",
      "ko-KR": "아브구스트"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 83,
    "released": true,
    "skins": [
      {
        "id": "307801",
        "type": "default",
        "released": true
      },
      {
        "id": "307802",
        "type": "insight",
        "name": "广场的小小天地",
        "nameEn": "His Own Corner on the Square",
        "released": true
      }
    ],
    "defaultVariant": "307801"
  },
  {
    "id": "3076",
    "baseId": "3076",
    "names": {
      "zh-CN": "和平乌鲁",
      "zh-TW": "和平烏魯",
      "en-US": "Ulu",
      "ja-JP": "ウル",
      "ko-KR": "울루"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 84,
    "released": true,
    "skins": [
      {
        "id": "307601",
        "type": "default",
        "released": true
      },
      {
        "id": "307602",
        "type": "insight",
        "name": "星火梦见之物",
        "nameEn": "Flammy's Dream",
        "released": true
      }
    ],
    "defaultVariant": "307601"
  },
  {
    "id": "3075",
    "baseId": "3075",
    "names": {
      "zh-CN": "沙丝绒",
      "zh-TW": "沙絲絨",
      "en-US": "Desert Flannel",
      "ja-JP": "サンド・フランネル",
      "ko-KR": "데저트 플란넬"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 85,
    "released": true,
    "skins": [
      {
        "id": "307501",
        "type": "default",
        "released": true
      },
      {
        "id": "307502",
        "type": "insight",
        "name": "红沙特卖",
        "nameEn": "Red Desert Special Offer",
        "released": true
      },
      {
        "id": "307503",
        "type": "skin",
        "name": "野性的倾洒",
        "nameEn": "Call of the Wild",
        "released": true
      }
    ],
    "defaultVariant": "307501"
  },
  {
    "id": "3071",
    "baseId": "3071",
    "names": {
      "zh-CN": "坎吉拉",
      "zh-TW": "坎吉拉",
      "en-US": "Kanjira",
      "ja-JP": "カンジーラ",
      "ko-KR": "칸지라"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 86,
    "released": true,
    "skins": [
      {
        "id": "307101",
        "type": "default",
        "released": true
      },
      {
        "id": "307102",
        "type": "insight",
        "name": "小铃鼓",
        "nameEn": "Tambourine",
        "released": true
      },
      {
        "id": "307103",
        "type": "skin",
        "name": "午夜来客",
        "nameEn": "The Night Visitor",
        "released": true
      }
    ],
    "defaultVariant": "307101"
  },
  {
    "id": "3064",
    "baseId": "3064",
    "names": {
      "zh-CN": "挖掘艺术",
      "zh-TW": "挖掘藝術",
      "en-US": "Diggers",
      "ja-JP": "ディガー",
      "ko-KR": "디거스"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 87,
    "released": true,
    "skins": [
      {
        "id": "306401",
        "type": "default",
        "released": true
      },
      {
        "id": "306402",
        "type": "insight",
        "name": "艺术挖掘者",
        "nameEn": "The Digger of Art",
        "released": true
      },
      {
        "id": "306403",
        "type": "skin",
        "name": "第三种假设",
        "nameEn": "Another Assumption",
        "released": true
      }
    ],
    "defaultVariant": "306401"
  },
  {
    "id": "3061",
    "baseId": "3061",
    "names": {
      "zh-CN": "恐怖通",
      "zh-TW": "恐怖通",
      "en-US": "Horropedia",
      "ja-JP": "ホラーペディア",
      "ko-KR": "호러피디아"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 88,
    "released": true,
    "skins": [
      {
        "id": "306101",
        "type": "default",
        "released": true
      },
      {
        "id": "306102",
        "type": "insight",
        "name": "惊叫主义",
        "nameEn": "Scarysm",
        "released": true
      },
      {
        "id": "306103",
        "type": "skin",
        "name": "疯道人",
        "nameEn": "A Daoist's Madness",
        "released": true
      }
    ],
    "defaultVariant": "306101"
  },
  {
    "id": "3060",
    "baseId": "3060",
    "names": {
      "zh-CN": "金蜜儿",
      "zh-TW": "金蜜兒",
      "en-US": "Blonney",
      "ja-JP": "ジェイミー",
      "ko-KR": "블로니"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 89,
    "released": true,
    "skins": [
      {
        "id": "306001",
        "type": "default",
        "released": true
      },
      {
        "id": "306002",
        "type": "insight",
        "name": "粉-粉-粉色女郎",
        "nameEn": "P-P-Pink Lady",
        "released": true
      },
      {
        "id": "306003",
        "type": "skin",
        "name": "铅黄色磨坊",
        "nameEn": "The Giallo Grind",
        "released": true
      }
    ],
    "defaultVariant": "306001"
  },
  {
    "id": "3049",
    "baseId": "3049",
    "names": {
      "zh-CN": "喀嚓喀嚓",
      "zh-TW": "喀嚓喀嚓",
      "en-US": "Click",
      "ja-JP": "カシャパシャ",
      "ko-KR": "클릭"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 90,
    "released": true,
    "skins": [
      {
        "id": "304901",
        "type": "default",
        "released": true
      },
      {
        "id": "304902",
        "type": "insight",
        "name": "绝妙的角度",
        "nameEn": "The Best Angle",
        "released": true
      }
    ],
    "defaultVariant": "304901"
  },
  {
    "id": "3043",
    "baseId": "3043",
    "names": {
      "zh-CN": "坦南特",
      "zh-TW": "坦南特",
      "en-US": "Tennant",
      "ja-JP": "テナント",
      "ko-KR": "테넌트"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 91,
    "released": true,
    "skins": [
      {
        "id": "304301",
        "type": "default",
        "released": true
      },
      {
        "id": "304302",
        "type": "insight",
        "name": "库里南绅士",
        "nameEn": "Gent Cullinan",
        "released": true
      },
      {
        "id": "304303",
        "type": "skin",
        "name": "德里漫步",
        "nameEn": "Roaming in Delhi",
        "released": true
      },
      {
        "id": "304304",
        "type": "skin",
        "name": "鉴赏家之战",
        "nameEn": "Dueling Connoisseurs",
        "released": true
      }
    ],
    "defaultVariant": "304301"
  },
  {
    "id": "3041",
    "baseId": "3041",
    "names": {
      "zh-CN": "玛蒂尔达",
      "zh-TW": "瑪蒂爾達",
      "en-US": "Matilda",
      "ja-JP": "マチルダ",
      "ko-KR": "마틸다"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 92,
    "released": true,
    "skins": [
      {
        "id": "304101",
        "type": "default",
        "released": true
      },
      {
        "id": "304102",
        "type": "insight",
        "name": "首席淑女",
        "nameEn": "Élève Hyperdouée",
        "released": true
      },
      {
        "id": "304103",
        "type": "skin",
        "name": "天才假日",
        "nameEn": "The Genius's Holiday",
        "released": true
      },
      {
        "id": "304104",
        "type": "skin",
        "name": "尝鲜调查员",
        "nameEn": "The Great Taste Investigator",
        "released": true
      }
    ],
    "defaultVariant": "304101"
  },
  {
    "id": "3038",
    "baseId": "3038",
    "names": {
      "zh-CN": "五色月",
      "zh-TW": "五色月",
      "en-US": "Satsuki",
      "ja-JP": "五色月",
      "ko-KR": "사츠키"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 93,
    "released": true,
    "skins": [
      {
        "id": "303801",
        "type": "default",
        "released": true
      },
      {
        "id": "303802",
        "type": "insight",
        "name": "苇中花",
        "nameEn": "Reed Bloom",
        "released": true
      },
      {
        "id": "303803",
        "type": "skin",
        "name": "银玫瑰",
        "nameEn": "Silver Rose",
        "released": true
      }
    ],
    "defaultVariant": "303801"
  },
  {
    "id": "3037",
    "baseId": "3037",
    "names": {
      "zh-CN": "讣告人",
      "zh-TW": "訃告人",
      "en-US": "Necrologist",
      "ja-JP": "ネクロ・ロギスト",
      "ko-KR": "네크롤로지스트"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 94,
    "released": true,
    "skins": [
      {
        "id": "303701",
        "type": "default",
        "released": true
      },
      {
        "id": "303702",
        "type": "insight",
        "name": "最后的诉说",
        "nameEn": "Last Words",
        "released": true
      },
      {
        "id": "303703",
        "type": "skin",
        "name": "永不返航",
        "nameEn": "A Voyage with No Return",
        "released": true
      }
    ],
    "defaultVariant": "303701"
  },
  {
    "id": "3024",
    "baseId": "3024",
    "names": {
      "zh-CN": "气球派对",
      "zh-TW": "氣球派對",
      "en-US": "Balloon Party",
      "ja-JP": "バルーンパーティー",
      "ko-KR": "벌룬 파티"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 95,
    "released": true,
    "skins": [
      {
        "id": "302401",
        "type": "default",
        "released": true
      },
      {
        "id": "302402",
        "type": "insight",
        "name": "不请自来的客人",
        "nameEn": "An Uninvited Guest",
        "released": true
      },
      {
        "id": "302403",
        "type": "skin",
        "name": "银翅谣",
        "nameEn": "The Folk Song of Silver Butterfly",
        "released": true
      }
    ],
    "defaultVariant": "302401"
  },
  {
    "id": "3023",
    "baseId": "3023",
    "names": {
      "zh-CN": "十四行诗",
      "zh-TW": "十四行詩",
      "en-US": "Sonetto",
      "ja-JP": "ソネット",
      "ko-KR": "소네트"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 96,
    "released": true,
    "skins": [
      {
        "id": "302301",
        "type": "default",
        "released": true
      },
      {
        "id": "302303",
        "type": "skin",
        "name": "巡礼颂",
        "nameEn": "Parade Anthem",
        "released": true
      },
      {
        "id": "302304",
        "type": "skin",
        "name": "重叠的词句",
        "nameEn": "Emotion in Tranquility",
        "released": true
      },
      {
        "id": "302306",
        "type": "skin",
        "name": "诗的礼赞",
        "nameEn": "In Praise of Poetry",
        "released": false
      }
    ],
    "defaultVariant": "302301"
  },
  {
    "id": "3022",
    "baseId": "3022",
    "names": {
      "zh-CN": "帕米埃",
      "zh-TW": "帕米埃",
      "en-US": "Dikke",
      "ja-JP": "パミエ",
      "ko-KR": "디케"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 97,
    "released": true,
    "skins": [
      {
        "id": "302201",
        "type": "default",
        "released": true
      },
      {
        "id": "302202",
        "type": "insight",
        "name": "汉谟拉比之剑",
        "nameEn": "Sword of Hammurabi",
        "released": true
      },
      {
        "id": "302203",
        "type": "skin",
        "name": "枪尖向上",
        "nameEn": "The Pointy End Up",
        "released": true
      }
    ],
    "defaultVariant": "302201"
  },
  {
    "id": "3020",
    "baseId": "3020",
    "names": {
      "zh-CN": "柏林以东",
      "zh-TW": "柏林以東",
      "en-US": "Bkornblume",
      "ja-JP": "コーンブルメ",
      "ko-KR": "콘블룸"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 98,
    "released": true,
    "skins": [
      {
        "id": "302001",
        "type": "default",
        "released": true
      },
      {
        "id": "302002",
        "type": "insight",
        "name": "不合时宜者",
        "nameEn": "The Misfit",
        "released": true
      },
      {
        "id": "302003",
        "type": "skin",
        "name": "铅红的真相",
        "nameEn": "Truth of the Dark Red",
        "released": true
      }
    ],
    "defaultVariant": "302001"
  },
  {
    "id": "3017",
    "baseId": "3017",
    "names": {
      "zh-CN": "夏利",
      "zh-TW": "夏利",
      "en-US": "Charlie",
      "ja-JP": "チャーリー",
      "ko-KR": "찰리"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 99,
    "released": true,
    "skins": [
      {
        "id": "301701",
        "type": "default",
        "released": true
      },
      {
        "id": "301702",
        "type": "insight",
        "name": "幻影中的国王",
        "nameEn": "The Tyrant in Illusion",
        "released": true
      },
      {
        "id": "301703",
        "type": "skin",
        "name": "镜中幕间",
        "nameEn": "Through Mirrors and Curtains",
        "released": true
      }
    ],
    "defaultVariant": "301701"
  },
  {
    "id": "3016",
    "baseId": "3016",
    "names": {
      "zh-CN": "婴儿蓝",
      "zh-TW": "嬰兒藍",
      "en-US": "Baby Blue",
      "ja-JP": "ベビーブルー",
      "ko-KR": "베이비 블루"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 100,
    "released": true,
    "skins": [
      {
        "id": "301601",
        "type": "default",
        "released": true
      },
      {
        "id": "301602",
        "type": "insight",
        "name": "新“红皇后”",
        "nameEn": "The New \"Red Queen\"",
        "released": true
      },
      {
        "id": "301603",
        "type": "skin",
        "name": "于麻雀山上",
        "nameEn": "On the Sparrow Hills ",
        "released": true
      }
    ],
    "defaultVariant": "301601"
  },
  {
    "id": "3011",
    "baseId": "3011",
    "names": {
      "zh-CN": "玛丽莲",
      "zh-TW": "瑪麗蓮",
      "en-US": "Sweetheart",
      "ja-JP": "スイートハート",
      "ko-KR": "마릴린"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 101,
    "released": true,
    "skins": [
      {
        "id": "301101",
        "type": "default",
        "released": true
      },
      {
        "id": "301102",
        "type": "insight",
        "name": "甜蜜的晚安",
        "nameEn": "Sweet Nighty Night",
        "released": true
      },
      {
        "id": "301103",
        "type": "skin",
        "name": "维纳斯的传道",
        "nameEn": "The Preaching of Venus",
        "released": true
      }
    ],
    "defaultVariant": "301101"
  },
  {
    "id": "3010",
    "baseId": "3010",
    "names": {
      "zh-CN": "X",
      "zh-TW": "X",
      "en-US": "X",
      "ja-JP": "X",
      "ko-KR": "X"
    },
    "rarity": 4,
    "maxInsight": 3,
    "releaseOrder": 102,
    "released": true,
    "skins": [
      {
        "id": "301001",
        "type": "default",
        "released": true
      },
      {
        "id": "301002",
        "type": "insight",
        "name": "“无用”的天才",
        "nameEn": "Genius of Useless Inventions",
        "released": true
      },
      {
        "id": "301003",
        "type": "skin",
        "name": "沉默的呼吸",
        "nameEn": "Silent Breath",
        "released": true
      }
    ],
    "defaultVariant": "301001"
  },
  {
    "id": "3151",
    "baseId": "3151",
    "names": {
      "zh-CN": "诺拉",
      "zh-TW": "諾拉",
      "en-US": "NORA",
      "ja-JP": "ノラ",
      "ko-KR": "노라"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 103,
    "released": true,
    "skins": [
      {
        "id": "315101",
        "type": "default",
        "released": true
      },
      {
        "id": "315102",
        "type": "insight",
        "name": "缱绻的心巢",
        "nameEn": "Nest of Love",
        "released": true
      }
    ],
    "defaultVariant": "315101"
  },
  {
    "id": "3138",
    "baseId": "3138",
    "names": {
      "zh-CN": "芦草结",
      "zh-TW": "蘆草結",
      "en-US": "Reed",
      "ja-JP": "リードノット",
      "ko-KR": "노초결"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 104,
    "released": true,
    "skins": [
      {
        "id": "313801",
        "type": "default",
        "released": true
      },
      {
        "id": "313802",
        "type": "insight",
        "name": "不息的沙沙声",
        "nameEn": "The Everlasting Scribbler",
        "released": true
      }
    ],
    "defaultVariant": "313801"
  },
  {
    "id": "3136",
    "baseId": "3136",
    "names": {
      "zh-CN": "《湖边的女人》",
      "zh-TW": "《湖邊的女人》",
      "en-US": "<i>Lady by the Lake</i>",
      "ja-JP": "『湖畔の女性』",
      "ko-KR": "<호숫가의 여인>"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 105,
    "released": true,
    "skins": [
      {
        "id": "313601",
        "type": "default",
        "released": true
      },
      {
        "id": "313602",
        "type": "insight",
        "name": "一个春日的记忆",
        "nameEn": "Memories of Spring",
        "released": true
      }
    ],
    "defaultVariant": "313601"
  },
  {
    "id": "3101",
    "baseId": "3101",
    "names": {
      "zh-CN": "白朗姆",
      "zh-TW": "白朗姆",
      "en-US": "White Rum",
      "ja-JP": "ホワイトラム",
      "ko-KR": "화이트 럼"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 106,
    "released": true,
    "skins": [
      {
        "id": "310101",
        "type": "default",
        "released": true
      },
      {
        "id": "310102",
        "type": "insight",
        "name": "瓶中小世界",
        "nameEn": "Big World in a Small Bottle",
        "released": true
      },
      {
        "id": "310103",
        "type": "skin",
        "name": "寰宇行舟",
        "nameEn": "Sailing Around the World",
        "released": true
      }
    ],
    "defaultVariant": "310101"
  },
  {
    "id": "3058",
    "baseId": "3058",
    "names": {
      "zh-CN": "埃里克",
      "zh-TW": "埃里克",
      "en-US": "Erick",
      "ja-JP": "エリック",
      "ko-KR": "에릭"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 107,
    "released": true,
    "skins": [
      {
        "id": "305801",
        "type": "default",
        "released": true
      },
      {
        "id": "305802",
        "type": "insight",
        "name": "孩子王",
        "nameEn": "The Great Jarl Erick",
        "released": true
      },
      {
        "id": "305803",
        "type": "skin",
        "name": "誓言与加值",
        "nameEn": "Oaths and Bonuses",
        "released": true
      }
    ],
    "defaultVariant": "305801"
  },
  {
    "id": "3057",
    "baseId": "3057",
    "names": {
      "zh-CN": "小梅斯梅尔",
      "zh-TW": "小梅斯梅爾",
      "en-US": "Mesmer Jr.",
      "ja-JP": "メスメル・Jr.",
      "ko-KR": "메스머 주니어"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 108,
    "released": true,
    "skins": [
      {
        "id": "305701",
        "type": "default",
        "released": true
      },
      {
        "id": "305702",
        "type": "insight",
        "name": "工具理性主义者",
        "nameEn": "The Instrumentalist & Rationalist",
        "released": true
      },
      {
        "id": "305703",
        "type": "skin",
        "name": "休假日",
        "nameEn": "A Day to Rest",
        "released": true
      }
    ],
    "defaultVariant": "305701"
  },
  {
    "id": "3046",
    "baseId": "3046",
    "names": {
      "zh-CN": "吵闹鬼",
      "zh-TW": "吵鬧鬼",
      "en-US": "Poltergeist",
      "ja-JP": "ポルターガイスト",
      "ko-KR": "폴터가이스트"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 109,
    "released": true,
    "skins": [
      {
        "id": "304601",
        "type": "default",
        "released": true
      },
      {
        "id": "304602",
        "type": "insight",
        "name": "羞怯的夏日",
        "nameEn": "Summertime Shyness",
        "released": true
      },
      {
        "id": "304603",
        "type": "skin",
        "name": "另一个夏日",
        "nameEn": "Under a Different Sea",
        "released": true
      }
    ],
    "defaultVariant": "304601"
  },
  {
    "id": "3044",
    "baseId": "3044",
    "names": {
      "zh-CN": "莫桑女士",
      "zh-TW": "莫桑女士",
      "en-US": "Ms. Moissan",
      "ja-JP": "ミス・モアッサン",
      "ko-KR": "무아상"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 110,
    "released": true,
    "skins": [
      {
        "id": "304401",
        "type": "default",
        "released": true
      },
      {
        "id": "304402",
        "type": "insight",
        "name": "另一种答案",
        "nameEn": "Another Answer",
        "released": true
      },
      {
        "id": "304403",
        "type": "skin",
        "name": "教堂之外",
        "nameEn": "Outside the Church",
        "released": true
      }
    ],
    "defaultVariant": "304401"
  },
  {
    "id": "3042",
    "baseId": "3042",
    "names": {
      "zh-CN": "爱宠",
      "zh-TW": "愛寵",
      "en-US": "Rabies",
      "ja-JP": "レイビーズ",
      "ko-KR": "레이비스"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 111,
    "released": true,
    "skins": [
      {
        "id": "304201",
        "type": "default",
        "released": true
      },
      {
        "id": "304202",
        "type": "insight",
        "name": "麦田守望者",
        "nameEn": "Catcher in the Rye",
        "released": true
      },
      {
        "id": "304203",
        "type": "skin",
        "name": "深空环游记",
        "nameEn": "Space Traveler",
        "released": true
      }
    ],
    "defaultVariant": "304201"
  },
  {
    "id": "3033",
    "baseId": "3033",
    "names": {
      "zh-CN": "TTT",
      "zh-TW": "TTT",
      "en-US": "TTT",
      "ja-JP": "TTT",
      "ko-KR": "TTT"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 112,
    "released": true,
    "skins": [
      {
        "id": "303301",
        "type": "default",
        "released": true
      },
      {
        "id": "303302",
        "type": "insight",
        "name": "新时代镜中人",
        "nameEn": "The Girl in the Frame",
        "released": true
      },
      {
        "id": "303303",
        "type": "skin",
        "name": "周六特别秀",
        "nameEn": "Saturday Special",
        "released": true
      }
    ],
    "defaultVariant": "303301"
  },
  {
    "id": "3031",
    "baseId": "3031",
    "names": {
      "zh-CN": "铅玻璃",
      "zh-TW": "鉛玻璃",
      "en-US": "Cristallo",
      "ja-JP": "クリスタッロ",
      "ko-KR": "크리스탈로"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 113,
    "released": true,
    "skins": [
      {
        "id": "303101",
        "type": "default",
        "released": true
      },
      {
        "id": "303102",
        "type": "insight",
        "name": "赠与勇敢者的花束",
        "nameEn": "Bouquet for the Bold",
        "released": true
      },
      {
        "id": "303103",
        "type": "skin",
        "name": "玻璃窗前的梦",
        "nameEn": "A Dream in Stained Glass",
        "released": true
      }
    ],
    "defaultVariant": "303101"
  },
  {
    "id": "3028",
    "baseId": "3028",
    "names": {
      "zh-CN": "APPLe",
      "zh-TW": "Apple",
      "en-US": "APPLe",
      "ja-JP": "APPLe",
      "ko-KR": "APPLe"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 114,
    "released": true,
    "skins": [
      {
        "id": "302801",
        "type": "default",
        "released": true
      },
      {
        "id": "302802",
        "type": "insight",
        "name": "博学而多汁",
        "nameEn": "Erudite and Juicy",
        "released": true
      },
      {
        "id": "302803",
        "type": "skin",
        "name": "胡士托的回声",
        "nameEn": "Echoing to Woodstock",
        "released": true
      },
      {
        "id": "302804",
        "type": "skin",
        "name": "智慧尽头",
        "nameEn": "The Fruit of Wisdom",
        "released": true
      }
    ],
    "defaultVariant": "302801"
  },
  {
    "id": "3026",
    "baseId": "3026",
    "names": {
      "zh-CN": "红斗篷",
      "zh-TW": "紅斗篷",
      "en-US": "Mondlicht",
      "ja-JP": "モントリヒト",
      "ko-KR": "빨간 망토"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 115,
    "released": true,
    "skins": [
      {
        "id": "302601",
        "type": "default",
        "released": true
      },
      {
        "id": "302602",
        "type": "insight",
        "name": "黑猎枪",
        "nameEn": "Black Rifle",
        "released": true
      },
      {
        "id": "302603",
        "type": "skin",
        "name": "银枪管",
        "nameEn": "Silver Schirm",
        "released": true
      }
    ],
    "defaultVariant": "302601"
  },
  {
    "id": "3018",
    "baseId": "3018",
    "names": {
      "zh-CN": "雾行者",
      "zh-TW": "霧行者",
      "en-US": "Oliver Fog",
      "ja-JP": "オリバー・フォッグ",
      "ko-KR": "올리버 포그"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 116,
    "released": true,
    "skins": [
      {
        "id": "301801",
        "type": "default",
        "released": true
      },
      {
        "id": "301802",
        "type": "insight",
        "name": "钟声响起",
        "nameEn": "When the Bell Rings",
        "released": true
      },
      {
        "id": "301803",
        "type": "skin",
        "name": "在俱乐部见",
        "nameEn": "See You at the Workers' Club",
        "released": true
      }
    ],
    "defaultVariant": "301801"
  },
  {
    "id": "3015",
    "baseId": "3015",
    "names": {
      "zh-CN": "狼群",
      "zh-TW": "狼群",
      "en-US": "Pavia",
      "ja-JP": "パヴィア",
      "ko-KR": "파비아"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 117,
    "released": true,
    "skins": [
      {
        "id": "301501",
        "type": "default",
        "released": true
      },
      {
        "id": "301502",
        "type": "insight",
        "name": "我亲爱的好朋友们",
        "nameEn": "My Dear Good friends",
        "released": true
      },
      {
        "id": "301503",
        "type": "skin",
        "name": "狼之跃",
        "nameEn": "The Wolf's Leap",
        "released": true
      }
    ],
    "defaultVariant": "301501"
  },
  {
    "id": "3014",
    "baseId": "3014",
    "names": {
      "zh-CN": "芭妮芭妮",
      "zh-TW": "芭妮芭妮",
      "en-US": "Bunny Bunny",
      "ja-JP": "バニーバニー",
      "ko-KR": "바니바니"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 118,
    "released": true,
    "skins": [
      {
        "id": "301401",
        "type": "default",
        "released": true
      },
      {
        "id": "301402",
        "type": "insight",
        "name": "最优兔女郎",
        "nameEn": "Bunny Girl of the Year",
        "released": true
      },
      {
        "id": "301403",
        "type": "skin",
        "name": "侍者的一天",
        "nameEn": "Service Fit for Royalty",
        "released": true
      }
    ],
    "defaultVariant": "301401"
  },
  {
    "id": "3013",
    "baseId": "3013",
    "names": {
      "zh-CN": "冬",
      "zh-TW": "冬",
      "en-US": "Зима",
      "ja-JP": "ズィマー",
      "ko-KR": "겨울"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 119,
    "released": true,
    "skins": [
      {
        "id": "301301",
        "type": "default",
        "released": true
      },
      {
        "id": "301302",
        "type": "insight",
        "name": "无人问津",
        "nameEn": "The Loner",
        "released": true
      },
      {
        "id": "301303",
        "type": "skin",
        "name": "山中一日",
        "nameEn": "A Day in the Mountain",
        "released": true
      }
    ],
    "defaultVariant": "301301"
  },
  {
    "id": "3006",
    "baseId": "3006",
    "names": {
      "zh-CN": "小春雀儿",
      "zh-TW": "小春雀兒",
      "en-US": "Eagle",
      "ja-JP": "リトルイーグル",
      "ko-KR": "이글"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 120,
    "released": true,
    "skins": [
      {
        "id": "300601",
        "type": "default",
        "released": true
      },
      {
        "id": "300602",
        "type": "insight",
        "name": "另一条路",
        "nameEn": "The Other Path",
        "released": true
      },
      {
        "id": "300603",
        "type": "skin",
        "name": "第六感",
        "nameEn": "Redrum",
        "released": true
      },
      {
        "id": "300604",
        "type": "skin",
        "name": "周末探险小队",
        "nameEn": "Weekend Excursion",
        "released": true
      }
    ],
    "defaultVariant": "300601"
  },
  {
    "id": "3005",
    "baseId": "3005",
    "names": {
      "zh-CN": "尼克·波顿",
      "zh-TW": "尼克·波頓",
      "en-US": "Nick Bottom",
      "ja-JP": "ニック・ボトム",
      "ko-KR": "닉 보텀"
    },
    "rarity": 3,
    "maxInsight": 2,
    "releaseOrder": 121,
    "released": true,
    "skins": [
      {
        "id": "300501",
        "type": "default",
        "released": true
      },
      {
        "id": "300502",
        "type": "insight",
        "name": "仲夏夜之梦",
        "nameEn": "A Midsummer Night's Dream",
        "released": true
      },
      {
        "id": "300503",
        "type": "skin",
        "name": "“波顿的梦”",
        "nameEn": "\"Bottom's Dream\"",
        "released": true
      }
    ],
    "defaultVariant": "300501"
  },
  {
    "id": "3096",
    "baseId": "3096",
    "names": {
      "zh-CN": "先驱者",
      "zh-TW": "先驅者",
      "en-US": "Pioneer",
      "ja-JP": "パイオニア",
      "ko-KR": "파이오니어"
    },
    "rarity": 2,
    "maxInsight": 2,
    "releaseOrder": 122,
    "released": true,
    "skins": [
      {
        "id": "309601",
        "type": "default",
        "released": true
      },
      {
        "id": "309602",
        "type": "insight",
        "name": "肌肤矫饰物",
        "nameEn": "Idol Fascinations",
        "released": true
      }
    ],
    "defaultVariant": "309601"
  },
  {
    "id": "3055",
    "baseId": "3055",
    "names": {
      "zh-CN": "斯普特尼克",
      "zh-TW": "斯普特尼克",
      "en-US": "Sputnik",
      "ja-JP": "スプートニク",
      "ko-KR": "스푸트니크"
    },
    "rarity": 2,
    "maxInsight": 2,
    "releaseOrder": 123,
    "released": true,
    "skins": [
      {
        "id": "305501",
        "type": "default",
        "released": true
      },
      {
        "id": "305502",
        "type": "insight",
        "name": "吱，吱吱？！",
        "nameEn": "Eek, Eek!",
        "released": true
      }
    ],
    "defaultVariant": "305501"
  },
  {
    "id": "3054",
    "baseId": "3054",
    "names": {
      "zh-CN": "洋葱头",
      "zh-TW": "洋蔥頭",
      "en-US": "ONiON",
      "ja-JP": "オニオン",
      "ko-KR": "어니언"
    },
    "rarity": 2,
    "maxInsight": 2,
    "releaseOrder": 124,
    "released": true,
    "skins": [
      {
        "id": "305401",
        "type": "default",
        "released": true
      },
      {
        "id": "305403",
        "type": "skin",
        "name": "体育快讯",
        "nameEn": "Front Page Exclusive",
        "released": false
      }
    ],
    "defaultVariant": "305401"
  },
  {
    "id": "3050",
    "baseId": "3050",
    "names": {
      "zh-CN": "哒哒达利",
      "zh-TW": "噠噠達利",
      "en-US": "Darley Clatter",
      "ja-JP": "ダーレータッタ",
      "ko-KR": "다그닥 달리"
    },
    "rarity": 2,
    "maxInsight": 2,
    "releaseOrder": 125,
    "released": true,
    "skins": [
      {
        "id": "305001",
        "type": "default",
        "released": true
      },
      {
        "id": "305002",
        "type": "insight",
        "name": "盛装舞步",
        "nameEn": "Elegant Dance Steps",
        "released": true
      }
    ],
    "defaultVariant": "305001"
  },
  {
    "id": "3045",
    "baseId": "3045",
    "names": {
      "zh-CN": "贝蒂",
      "zh-TW": "貝蒂",
      "en-US": "Bette",
      "ja-JP": "ベティ",
      "ko-KR": "베티"
    },
    "rarity": 2,
    "maxInsight": 2,
    "releaseOrder": 126,
    "released": true,
    "skins": [
      {
        "id": "304501",
        "type": "default",
        "released": true
      },
      {
        "id": "304504",
        "type": "skin",
        "name": "人生填色格",
        "nameEn": "A Life in Frames",
        "released": false
      }
    ],
    "defaultVariant": "304501"
  },
  {
    "id": "3040",
    "baseId": "3040",
    "names": {
      "zh-CN": "丽莎&路易斯",
      "zh-TW": "麗莎&路易斯",
      "en-US": "Twins Sleep",
      "ja-JP": "リサ＆ルイス",
      "ko-KR": "리사&루이스"
    },
    "rarity": 2,
    "maxInsight": 2,
    "releaseOrder": 127,
    "released": true,
    "skins": [
      {
        "id": "304001",
        "type": "default",
        "released": true
      },
      {
        "id": "304002",
        "type": "insight",
        "name": "升变华尔兹",
        "nameEn": "The Pawn's Promotional Waltz",
        "released": true
      }
    ],
    "defaultVariant": "304001"
  },
  {
    "id": "3036",
    "baseId": "3036",
    "names": {
      "zh-CN": "约翰·提托",
      "zh-TW": "約翰·提托",
      "en-US": "John Titor",
      "ja-JP": "ジョン・タイター",
      "ko-KR": "존 티토"
    },
    "rarity": 2,
    "maxInsight": 2,
    "releaseOrder": 128,
    "released": true,
    "skins": [
      {
        "id": "303601",
        "type": "default",
        "released": true
      },
      {
        "id": "303602",
        "type": "insight",
        "name": "疾步向前",
        "nameEn": "Race to the Finish Line",
        "released": true
      }
    ],
    "defaultVariant": "303601"
  },
  {
    "id": "3035",
    "baseId": "3035",
    "names": {
      "zh-CN": "莉拉妮",
      "zh-TW": "莉拉妮",
      "en-US": "Leilani",
      "ja-JP": "レイラニ",
      "ko-KR": "레일라니"
    },
    "rarity": 2,
    "maxInsight": 2,
    "releaseOrder": 129,
    "released": true,
    "skins": [
      {
        "id": "303501",
        "type": "default",
        "released": true
      },
      {
        "id": "303502",
        "type": "insight",
        "name": "远峰的巡游",
        "nameEn": "The Adventure on The Mountains",
        "released": true
      }
    ],
    "defaultVariant": "303501"
  },
  {
    "id": "3034",
    "baseId": "3034",
    "names": {
      "zh-CN": "星之眼",
      "zh-TW": "星之眼",
      "en-US": "aliEn T",
      "ja-JP": "ギベオンズアイ",
      "ko-KR": "에일리언 T"
    },
    "rarity": 2,
    "maxInsight": 2,
    "releaseOrder": 130,
    "released": true,
    "skins": [
      {
        "id": "303401",
        "type": "default",
        "released": true
      }
    ],
    "defaultVariant": "303401"
  },
  {
    "id": "3030",
    "baseId": "3030",
    "names": {
      "zh-CN": "拉拉泉",
      "zh-TW": "拉拉泉",
      "en-US": "La Source",
      "ja-JP": "ララ・ファウンテン",
      "ko-KR": "라 수르스"
    },
    "rarity": 2,
    "maxInsight": 2,
    "releaseOrder": 131,
    "released": true,
    "skins": [
      {
        "id": "303001",
        "type": "default",
        "released": true
      },
      {
        "id": "303002",
        "type": "insight",
        "name": "二律背反",
        "nameEn": "Antinomies",
        "released": true
      }
    ],
    "defaultVariant": "303001"
  },
  {
    "id": "3012",
    "baseId": "3012",
    "names": {
      "zh-CN": "弄臣",
      "zh-TW": "弄臣",
      "en-US": "The Fool",
      "ja-JP": "ジェスター",
      "ko-KR": "광대"
    },
    "rarity": 2,
    "maxInsight": 2,
    "releaseOrder": 132,
    "released": true,
    "skins": [
      {
        "id": "301201",
        "type": "default",
        "released": true
      },
      {
        "id": "301202",
        "type": "insight",
        "name": "影子巧挑班",
        "nameEn": "The Shadow Play Master",
        "released": true
      }
    ],
    "defaultVariant": "301201"
  },
  {
    "id": "3059",
    "baseId": "3059",
    "names": {
      "zh-CN": "门",
      "zh-TW": "門",
      "en-US": "Door",
      "ja-JP": "ドア",
      "ko-KR": "문"
    },
    "rarity": 1,
    "maxInsight": 2,
    "releaseOrder": 133,
    "released": true,
    "skins": [
      {
        "id": "305901",
        "type": "default",
        "released": true
      }
    ],
    "defaultVariant": "305901"
  },
  {
    "id": "3027",
    "baseId": "3027",
    "names": {
      "zh-CN": "无线电小姐",
      "zh-TW": "無線電小姐",
      "en-US": "Ms. Radio",
      "ja-JP": "ミス・ラジオ",
      "ko-KR": "미스 라디오"
    },
    "rarity": 1,
    "maxInsight": 2,
    "releaseOrder": 134,
    "released": true,
    "skins": [
      {
        "id": "302701",
        "type": "default",
        "released": true
      },
      {
        "id": "302702",
        "type": "insight",
        "name": "战地生命线",
        "nameEn": "Lifeline of the Battlefield",
        "released": true
      }
    ],
    "defaultVariant": "302701"
  }
];
