// Generated by scripts/build-psychubes.ts — CN∩GL baseline + manual overrides
import type { PsychubeDef } from "../types/catalog";

export const psychubes: PsychubeDef[] = [
  {
    "id": "1501",
    "names": {
      "zh-CN": "美丽新世界",
      "zh-TW": "美麗新世界",
      "en-US": "Brave New World",
      "ja-JP": "美しい新世界",
      "ko-KR": "멋진 신세계"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1502",
    "names": {
      "zh-CN": "跳房子游戏",
      "zh-TW": "跳房子遊戲",
      "en-US": "Hopscotch",
      "ja-JP": "ホップスコッチ",
      "ko-KR": "땅따먹기 게임"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1503",
    "names": {
      "zh-CN": "第二次生命",
      "zh-TW": "第二次生命",
      "en-US": "Her Second Life",
      "ja-JP": "二度目の人生",
      "ko-KR": "두 번째 생명"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1504",
    "names": {
      "zh-CN": "夜色亵渎者",
      "zh-TW": "夜色褻瀆者",
      "en-US": "Blasphemer of Night",
      "ja-JP": "夜を冒涜する者",
      "ko-KR": "밤의 모독자"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1507",
    "names": {
      "zh-CN": "掌声如雷鸣",
      "zh-TW": "掌聲如雷鳴",
      "en-US": "Thunderous Applause",
      "ja-JP": "万雷の拍手",
      "ko-KR": "우레와 같은 박수"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1508",
    "names": {
      "zh-CN": "好奇心宝贝",
      "zh-TW": "好奇心寶貝",
      "en-US": "That Inquisitive Dear",
      "ja-JP": "好奇心の塊",
      "ko-KR": "호기심쟁이"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1510",
    "names": {
      "zh-CN": "必要的记录",
      "zh-TW": "必要的記錄",
      "en-US": "His Bounden Duty",
      "ja-JP": "必要な記録",
      "ko-KR": "필요한 기록"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1509",
    "names": {
      "zh-CN": "大娱乐至上",
      "zh-TW": "大娛樂至上",
      "en-US": "Luxurious Leisure",
      "ja-JP": "娯楽至上",
      "ko-KR": "오락 지상주의"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1511",
    "names": {
      "zh-CN": "在仙境之外",
      "zh-TW": "在仙境之外",
      "en-US": "Beyond Wonderland",
      "ja-JP": "おとぎの国の外",
      "ko-KR": "원더랜드 너머"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1401",
    "names": {
      "zh-CN": "心驰神往",
      "zh-TW": "心馳神往",
      "en-US": "Yearning Desire",
      "ja-JP": "思いを馳せて",
      "ko-KR": "마음의 방향"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1402",
    "names": {
      "zh-CN": "明日亦然",
      "zh-TW": "明日亦然",
      "en-US": "Tomorrow Also",
      "ja-JP": "明日も同じ",
      "ko-KR": "똑같은 내일"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1404",
    "names": {
      "zh-CN": "无束无拘",
      "zh-TW": "無束無拘",
      "en-US": "The Footloose",
      "ja-JP": "気ままに",
      "ko-KR": "자유자재"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1405",
    "names": {
      "zh-CN": "示我以真",
      "zh-TW": "示我以真",
      "en-US": "Decode",
      "ja-JP": "むき出しの真実",
      "ko-KR": "진실된 나"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1407",
    "names": {
      "zh-CN": "午后小憩",
      "zh-TW": "午後小憩",
      "en-US": "An Afternoon Nap",
      "ja-JP": "午後の休憩",
      "ko-KR": "오후의 휴식"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1411",
    "names": {
      "zh-CN": "远大前程",
      "zh-TW": "遠大前程",
      "en-US": "Her Bright Future",
      "ja-JP": "遥かなる前途",
      "ko-KR": "원대한 여정"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "4103",
    "names": {
      "zh-CN": "自由的心",
      "zh-TW": "自由的心",
      "en-US": "A Free Heart",
      "ja-JP": "自由な心",
      "ko-KR": "자유의 마음"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "4104",
    "names": {
      "zh-CN": "笑语欢声",
      "zh-TW": "笑語歡聲",
      "en-US": "Laughter and Laughter",
      "ja-JP": "楽しげな笑い声",
      "ko-KR": "웃음소리"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1306",
    "names": {
      "zh-CN": "领航",
      "zh-TW": "領航",
      "en-US": "Navigating",
      "ja-JP": "航海",
      "ko-KR": "항해"
    },
    "rarity": 3,
    "released": true
  },
  {
    "id": "1307",
    "names": {
      "zh-CN": "崇奉",
      "zh-TW": "崇奉",
      "en-US": "Bow",
      "ja-JP": "崇奉",
      "ko-KR": "숭배"
    },
    "rarity": 3,
    "released": true
  },
  {
    "id": "1308",
    "names": {
      "zh-CN": "无餍",
      "zh-TW": "無饜",
      "en-US": "Covet",
      "ja-JP": "貪欲",
      "ko-KR": "갈망"
    },
    "rarity": 3,
    "released": true
  },
  {
    "id": "1309",
    "names": {
      "zh-CN": "绿毒",
      "zh-TW": "綠毒",
      "en-US": "Venomous",
      "ja-JP": "緑毒",
      "ko-KR": "푸른독"
    },
    "rarity": 3,
    "released": true
  },
  {
    "id": "1310",
    "names": {
      "zh-CN": "静谧",
      "zh-TW": "靜謐",
      "en-US": "Meek",
      "ja-JP": "静謐",
      "ko-KR": "고요"
    },
    "rarity": 3,
    "released": true
  },
  {
    "id": "1201",
    "names": {
      "zh-CN": "轻藐",
      "zh-TW": "輕藐",
      "en-US": "Slighted",
      "ja-JP": "軽蔑",
      "ko-KR": "경멸"
    },
    "rarity": 2,
    "released": true
  },
  {
    "id": "1202",
    "names": {
      "zh-CN": "蓬勃",
      "zh-TW": "蓬勃",
      "en-US": "Flourishing",
      "ja-JP": "鬱然",
      "ko-KR": "팽배"
    },
    "rarity": 2,
    "released": true
  },
  {
    "id": "1203",
    "names": {
      "zh-CN": "怅然",
      "zh-TW": "悵然",
      "en-US": "Loss",
      "ja-JP": "喪失",
      "ko-KR": "낙담"
    },
    "rarity": 2,
    "released": true
  },
  {
    "id": "1204",
    "names": {
      "zh-CN": "欢声",
      "zh-TW": "歡聲",
      "en-US": "Cheering",
      "ja-JP": "歓声",
      "ko-KR": "환호"
    },
    "rarity": 2,
    "released": true
  },
  {
    "id": "1205",
    "names": {
      "zh-CN": "麻木",
      "zh-TW": "麻木",
      "en-US": "Numb",
      "ja-JP": "無感覚",
      "ko-KR": "둔감"
    },
    "rarity": 2,
    "released": true
  },
  {
    "id": "1206",
    "names": {
      "zh-CN": "蒙昧",
      "zh-TW": "蒙昧",
      "en-US": "Fatuous",
      "ja-JP": "蒙昧",
      "ko-KR": "몽매"
    },
    "rarity": 2,
    "released": true
  },
  {
    "id": "1512",
    "names": {
      "zh-CN": "可度量之心",
      "zh-TW": "可度量之心",
      "en-US": "The Carat of a Heart",
      "ja-JP": "測定可能な心",
      "ko-KR": "헤아릴 수 있는 마음"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1513",
    "names": {
      "zh-CN": "沉默与向往",
      "zh-TW": "沉默與嚮往",
      "en-US": "Silent and Adoring",
      "ja-JP": "沈黙と憧れ",
      "ko-KR": "침묵과 동경"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1514",
    "names": {
      "zh-CN": "请保持平衡",
      "zh-TW": "請保持平衡",
      "en-US": "Balance, Please",
      "ja-JP": "バランスに注意",
      "ko-KR": "균형 유지"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1413",
    "names": {
      "zh-CN": "食足餮满",
      "zh-TW": "食足餮滿",
      "en-US": "A Satisfied Eater",
      "ja-JP": "サティスファイド・イーター",
      "ko-KR": "풍족한 식탁"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1414",
    "names": {
      "zh-CN": "荒唐余生",
      "zh-TW": "荒唐餘生",
      "en-US": "Remaining Absurdity",
      "ja-JP": "アブサーディティ・ライフ",
      "ko-KR": "황당한 여생"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1515",
    "names": {
      "zh-CN": "漫长悄悄话",
      "zh-TW": "漫長悄悄話",
      "en-US": "Long Night Talk",
      "ja-JP": "長い夜話",
      "ko-KR": "기나긴 속삭임"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1420",
    "names": {
      "zh-CN": "步此苦旅",
      "zh-TW": "步此苦旅",
      "en-US": "Take the Hard Journey",
      "ja-JP": "苦しい旅の途中",
      "ko-KR": "고통의 여정"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1421",
    "names": {
      "zh-CN": "勇往直前",
      "zh-TW": "勇往直前",
      "en-US": "Let's Set Sail",
      "ja-JP": "いざ出航",
      "ko-KR": "용감한 전진"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1521",
    "names": {
      "zh-CN": "在四方城外",
      "zh-TW": "在四方城外",
      "en-US": "Outside the City",
      "ja-JP": "四方城の外にて",
      "ko-KR": "성 밖의 세상"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1522",
    "names": {
      "zh-CN": "此刻无新事",
      "zh-TW": "此刻無新事",
      "en-US": "Same Old Story",
      "ja-JP": "目下に新事なし",
      "ko-KR": "평범한 순간"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1422",
    "names": {
      "zh-CN": "茶歇时间",
      "zh-TW": "茶歇時間",
      "en-US": "Tea Break",
      "ja-JP": "ティータイム",
      "ko-KR": "다과 시간"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1423",
    "names": {
      "zh-CN": "崭新一页",
      "zh-TW": "嶄新一頁",
      "en-US": "A New Leaf",
      "ja-JP": "新たなページ",
      "ko-KR": "새로운 종이"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1523",
    "names": {
      "zh-CN": "敲响这窄门",
      "zh-TW": "敲響這窄門",
      "en-US": "Knock on the Door",
      "ja-JP": "狭いドアをノックして",
      "ko-KR": "좁은 문을 두드려라"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1524",
    "names": {
      "zh-CN": "另一个故事",
      "zh-TW": "另一個故事",
      "en-US": "Another Story",
      "ja-JP": "もうひとつの物語",
      "ko-KR": "또 다른 이야기"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1424",
    "names": {
      "zh-CN": "昨日往事",
      "zh-TW": "昨日往事",
      "en-US": "His Tail",
      "ja-JP": "昨日の出来事",
      "ko-KR": "어제의 옛일"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1425",
    "names": {
      "zh-CN": "齿轮之外",
      "zh-TW": "齒輪之外",
      "en-US": "Beyond the Gears",
      "ja-JP": "歯車の外",
      "ko-KR": "톱니바퀴 너머"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1525",
    "names": {
      "zh-CN": "黎明将到来",
      "zh-TW": "黎明將到來",
      "en-US": "Dawn Is Coming",
      "ja-JP": "夜は明ける",
      "ko-KR": "새벽이 다가온다"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1526",
    "names": {
      "zh-CN": "故尝试证明",
      "zh-TW": "故嘗試證明",
      "en-US": "For Rehabilitation",
      "ja-JP": "証明の試み",
      "ko-KR": "증명 시도"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1426",
    "names": {
      "zh-CN": "夜夜亦然",
      "zh-TW": "夜夜亦然",
      "en-US": "Night After Night",
      "ja-JP": "夜な夜な",
      "ko-KR": "밤이면 밤마다"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1427",
    "names": {
      "zh-CN": "无声注视",
      "zh-TW": "無聲注視",
      "en-US": "Silent Gaze",
      "ja-JP": "沈黙の眼差し",
      "ko-KR": "소리 없는 응시"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1527",
    "names": {
      "zh-CN": "行进的步音",
      "zh-TW": "行進的步音",
      "en-US": "Steps Forward",
      "ja-JP": "前進の足音",
      "ko-KR": "행진의 걸음 소리"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1528",
    "names": {
      "zh-CN": "勇敢者赠言",
      "zh-TW": "勇敢者贈言",
      "en-US": "The Fighter's Best Wishes",
      "ja-JP": "勇ましい者の言葉",
      "ko-KR": "용자의 충고"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1529",
    "names": {
      "zh-CN": "渐近的雨声",
      "zh-TW": "漸近的雨聲",
      "en-US": "Approaching Rain",
      "ja-JP": "近づく雨の音",
      "ko-KR": "가까워지는 빗소리"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1428",
    "names": {
      "zh-CN": "形影相随",
      "zh-TW": "形影相隨",
      "en-US": "In the Shadow",
      "ja-JP": "影にて",
      "ko-KR": "그림자처럼"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1429",
    "names": {
      "zh-CN": "踽踽独行",
      "zh-TW": "踽踽獨行",
      "en-US": "Going Along Alone",
      "ja-JP": "ウォーク・アローン",
      "ko-KR": "고독한 걸음"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1530",
    "names": {
      "zh-CN": "来自最深处",
      "zh-TW": "來自最深處",
      "en-US": "From the Depths",
      "ja-JP": "最奥より",
      "ko-KR": "가장 깊은 곳에서"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1531",
    "names": {
      "zh-CN": "不可诉之轻",
      "zh-TW": "不可訴之輕",
      "en-US": "The Unbearable Lightness",
      "ja-JP": "語られざる軽さ",
      "ko-KR": "말할 수 없는 가벼움"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1532",
    "names": {
      "zh-CN": "漫行如泉流",
      "zh-TW": "漫行如泉流",
      "en-US": "Starlight Wellspring",
      "ja-JP": "流れゆく泉のように",
      "ko-KR": "샘물처럼 천천히"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1430",
    "names": {
      "zh-CN": "黯然失色",
      "zh-TW": "黯然失色",
      "en-US": "Her Mournful Face",
      "ja-JP": "デプレッション",
      "ko-KR": "무색"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1431",
    "names": {
      "zh-CN": "自食苦果",
      "zh-TW": "自食苦果",
      "en-US": "You Deserve It",
      "ja-JP": "自業自得",
      "ko-KR": "직접 맛본 쓴맛"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1533",
    "names": {
      "zh-CN": "女佣看见了",
      "zh-TW": "女傭看見了",
      "en-US": "And the Maid Says",
      "ja-JP": "メイドは見た",
      "ko-KR": "메이드의 목격"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1534",
    "names": {
      "zh-CN": "寻入夜深处",
      "zh-TW": "尋入夜深處",
      "en-US": "Stray Off the Path",
      "ja-JP": "夜の奥深くへと",
      "ko-KR": "밤의 깊은 곳"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1432",
    "names": {
      "zh-CN": "绘声绘色",
      "zh-TW": "繪聲繪色",
      "en-US": "Spinning Yarns",
      "ja-JP": "生気に満ちた物語",
      "ko-KR": "소리와 색"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1433",
    "names": {
      "zh-CN": "无人问津",
      "zh-TW": "無人問津",
      "en-US": "The Loner",
      "ja-JP": "知られざる芸術",
      "ko-KR": "무관심"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1536",
    "names": {
      "zh-CN": "非物质真情",
      "zh-TW": "非物質真情",
      "en-US": "Transcendent Love",
      "ja-JP": "愛の本質",
      "ko-KR": "실체 없는 진실"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1537",
    "names": {
      "zh-CN": "第三次信任",
      "zh-TW": "第三次信任",
      "en-US": "The Third Commitment",
      "ja-JP": "三度目の信頼",
      "ko-KR": "세 번째 신뢰"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1434",
    "names": {
      "zh-CN": "落于现象",
      "zh-TW": "落於現象",
      "en-US": "Falling for a Sweet Phenomenon",
      "ja-JP": "現象の中に落ちて",
      "ko-KR": "현상에 남다"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1435",
    "names": {
      "zh-CN": "留置心底",
      "zh-TW": "留置心底",
      "en-US": "The Severed and the Rest",
      "ja-JP": "心に刻み込んだもの",
      "ko-KR": "마음 속에 남겨진 것"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1535",
    "names": {
      "zh-CN": "微渺的愿景",
      "zh-TW": "微渺的願景",
      "en-US": "Tiny Wish",
      "ja-JP": "ささやかな願い",
      "ko-KR": "미미한 청사진"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1538",
    "names": {
      "zh-CN": "无韵律跳步",
      "zh-TW": "無韻律跳步",
      "en-US": "Offbeat Strides",
      "ja-JP": "ノンリズムジャンプ",
      "ko-KR": "불규칙한 스텝"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1539",
    "names": {
      "zh-CN": "秒针栖息地",
      "zh-TW": "秒針棲息地",
      "en-US": "On the Hand of Time",
      "ja-JP": "秒針の住み処",
      "ko-KR": "초침의 서식지"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1436",
    "names": {
      "zh-CN": "迷途以外",
      "zh-TW": "迷途以外",
      "en-US": "One with the Flow",
      "ja-JP": "迷道の外",
      "ko-KR": "미로의 밖"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1540",
    "names": {
      "zh-CN": "离别变奏曲",
      "zh-TW": "離別變奏曲",
      "en-US": "Addio Coda",
      "ja-JP": "別れの変奏曲",
      "ko-KR": "이별 변주곡"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1541",
    "names": {
      "zh-CN": "惶然的贝壳",
      "zh-TW": "惶然的貝殼",
      "en-US": "Cracks in the Shell",
      "ja-JP": "貝殻のひび割れ",
      "ko-KR": "두려워하는 조개껍데기"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1437",
    "names": {
      "zh-CN": "纵情一曲",
      "zh-TW": "縱情一曲",
      "en-US": "Belt It Out",
      "ja-JP": "ベルト・イット・アウト",
      "ko-KR": "열정의 노래"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1542",
    "names": {
      "zh-CN": "收到请回答",
      "zh-TW": "收到請回答",
      "en-US": "Ready on Call",
      "ja-JP": "直ちに応答せよ",
      "ko-KR": "응답 바람"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1543",
    "names": {
      "zh-CN": "造梦的预演",
      "zh-TW": "造夢的預演",
      "en-US": "Rehearsal of Dreams",
      "ja-JP": "夢づくりのリハーサル",
      "ko-KR": "꿈의 리허설"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1438",
    "names": {
      "zh-CN": "惊魂拍档",
      "zh-TW": "驚魂拍檔",
      "en-US": "Your Friendly Exorcist",
      "ja-JP": "除霊パートナー",
      "ko-KR": "친절한 퇴마사"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1544",
    "names": {
      "zh-CN": "最后的投掷",
      "zh-TW": "最後的投擲",
      "en-US": "The Final Roll",
      "ja-JP": "最後のダイス",
      "ko-KR": "마지막 던지기"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1545",
    "names": {
      "zh-CN": "脑室即囚室",
      "zh-TW": "腦室即囚室",
      "en-US": "Mental Cage",
      "ja-JP": "脳の牢獄",
      "ko-KR": "뇌실은 감옥이다"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1439",
    "names": {
      "zh-CN": "镜头注脚",
      "zh-TW": "鏡頭註腳",
      "en-US": "Off the Scene",
      "ja-JP": "舞台裏の注釈",
      "ko-KR": "장면 메모"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1546",
    "names": {
      "zh-CN": "双焦点问答",
      "zh-TW": "雙焦點問答",
      "en-US": "Never-Ending Q&A",
      "ja-JP": "終わらないQ&A",
      "ko-KR": "네버엔딩 Q&A"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1547",
    "names": {
      "zh-CN": "春日轻步至",
      "zh-TW": "春日輕步至",
      "en-US": "Aurora After Winter",
      "ja-JP": "春の足取り",
      "ko-KR": "살포시 다가오는 봄날"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1440",
    "names": {
      "zh-CN": "新旧歌谣",
      "zh-TW": "新舊歌謠",
      "en-US": "Melodies Old and New",
      "ja-JP": "懐かしい歌、新しいメロディー",
      "ko-KR": "올드앤뉴 멜로디"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1548",
    "names": {
      "zh-CN": "心音墓志铭",
      "zh-TW": "心音墓誌銘",
      "en-US": "Embrace the Past",
      "ja-JP": "心の墓碑銘",
      "ko-KR": "마음의 묘비명"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1549",
    "names": {
      "zh-CN": "家庭指导员",
      "zh-TW": "家庭指導員",
      "en-US": "Family Mentor",
      "ja-JP": "家族の導き手",
      "ko-KR": "가정 지도사"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1550",
    "names": {
      "zh-CN": "思维一激灵",
      "zh-TW": "思維一激靈",
      "en-US": "A Tingle of a Thought",
      "ja-JP": "ふとしたきらめき",
      "ko-KR": "떠오른 생각"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1441",
    "names": {
      "zh-CN": "路边尘埃",
      "zh-TW": "路邊塵埃",
      "en-US": "Dust on the Roadside",
      "ja-JP": "道端のほこり",
      "ko-KR": "길가의 먼지"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1553",
    "names": {
      "zh-CN": "归乡哀悼词",
      "zh-TW": "歸鄉哀悼詞",
      "en-US": "Homecoming Lament",
      "ja-JP": "帰郷の追悼",
      "ko-KR": "귀향의 애도사"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1554",
    "names": {
      "zh-CN": "向种子呢喃",
      "zh-TW": "向種子呢喃",
      "en-US": "Buds Yet to Bloom",
      "ja-JP": "種に囁きかけ",
      "ko-KR": "씨앗을 향한 속삭임"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1442",
    "names": {
      "zh-CN": "偷天换日",
      "zh-TW": "偷天換日",
      "en-US": "Substitutes and Simulacra",
      "ja-JP": "偽物と模造品",
      "ko-KR": "사기극"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1551",
    "names": {
      "zh-CN": "钟响于暮色",
      "zh-TW": "鐘響於暮色",
      "en-US": "As the Bell Tolls",
      "ja-JP": "黄昏に響く鐘",
      "ko-KR": "황혼의 종소리"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1552",
    "names": {
      "zh-CN": "史诗的终点",
      "zh-TW": "史詩的終點",
      "en-US": "An Epic's End",
      "ja-JP": "叙事詩の終焉",
      "ko-KR": "서사시의 끝"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1555",
    "names": {
      "zh-CN": "汇入涓流中",
      "zh-TW": "匯入涓流中",
      "en-US": "Into the Gentle Current",
      "ja-JP": "細流に流れ込んで",
      "ko-KR": "개울 속으로"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1556",
    "names": {
      "zh-CN": "流浪即兴曲",
      "zh-TW": "流浪即興曲",
      "en-US": "The Wandering Improviser",
      "ja-JP": "さすらいの即興曲",
      "ko-KR": "방랑 즉흥곡"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1557",
    "names": {
      "zh-CN": "生者的苦旅",
      "zh-TW": "生者的苦旅",
      "en-US": "Bitter March of the Living",
      "ja-JP": "残された者の旅",
      "ko-KR": "살아있는 자의 고행"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1443",
    "names": {
      "zh-CN": "碑文已逝",
      "zh-TW": "碑文已逝",
      "en-US": "Faded Epitaphs",
      "ja-JP": "色褪せたエピタフ",
      "ko-KR": "사라진 비문"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1558",
    "names": {
      "zh-CN": "千万次应验",
      "zh-TW": "千萬次應驗",
      "en-US": "The Thousandfold Fate",
      "ja-JP": "予言されし千万の運命",
      "ko-KR": "천만번의 효험"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1559",
    "names": {
      "zh-CN": "跃过命运线",
      "zh-TW": "躍過命運線",
      "en-US": "Her Willful Leap",
      "ja-JP": "運命を跳び越えて",
      "ko-KR": "운명의 선을 넘어"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1560",
    "names": {
      "zh-CN": "无意识梦魇",
      "zh-TW": "無意識夢魘",
      "en-US": "Shadows in the Subconscious",
      "ja-JP": "潜在意識の影",
      "ko-KR": "무의식의 악몽"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1444",
    "names": {
      "zh-CN": "“倒影”所指",
      "zh-TW": "“倒影”所指",
      "en-US": "In Their Figures",
      "ja-JP": "「投影」が指し示すもの",
      "ko-KR": "‘반사된 형상’의 지시"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1561",
    "names": {
      "zh-CN": "我心如赤焰",
      "zh-TW": "我心如赤焰",
      "en-US": "Singleness of Heart",
      "ja-JP": "澄みわたる真心",
      "ko-KR": "화염 같은 내 심장이여"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1562",
    "names": {
      "zh-CN": "行至阿刻戎",
      "zh-TW": "行至阿刻戎",
      "en-US": "Across the Acheron",
      "ja-JP": "アケロンを渡りて",
      "ko-KR": "아케론을 건너"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1445",
    "names": {
      "zh-CN": "世多别离",
      "zh-TW": "世多別離",
      "en-US": "Parting's Quiet Lament",
      "ja-JP": "別れの嘆き",
      "ko-KR": "수많은 이별"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1563",
    "names": {
      "zh-CN": "天地一悠游",
      "zh-TW": "天地一悠遊",
      "en-US": "Wayfarer of the Dao",
      "ja-JP": "天地悠遊",
      "ko-KR": "천지 유람"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1564",
    "names": {
      "zh-CN": "功名尘与土",
      "zh-TW": "功名塵與土",
      "en-US": "All Honor is but Dust",
      "ja-JP": "功名、塵芥に帰す",
      "ko-KR": "공명이란 티끌과 흙일 뿐"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1446",
    "names": {
      "zh-CN": "无事听风",
      "zh-TW": "無事聽風",
      "en-US": "The Wind's Listener",
      "ja-JP": "風に耳を傾けば",
      "ko-KR": "한가로이 듣는 바람"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1565",
    "names": {
      "zh-CN": "振翅一瞬间",
      "zh-TW": "振翅一瞬間",
      "en-US": "The Fluttering Moment",
      "ja-JP": "羽ばたきの刹那",
      "ko-KR": "날갯짓의 순간"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1566",
    "names": {
      "zh-CN": "世界多喧闹",
      "zh-TW": "世界多喧鬧",
      "en-US": "Drown Out the Hustle",
      "ja-JP": "喧騒を遠ざけて",
      "ko-KR": "소란스러운 세상"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1447",
    "names": {
      "zh-CN": "天助自助",
      "zh-TW": "天助自助",
      "en-US": "Luck Be a Lady",
      "ja-JP": "天は自ら助くる者を助く",
      "ko-KR": "하늘은 스스로 돕는 자를 돕는다"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1567",
    "names": {
      "zh-CN": "解答的边界",
      "zh-TW": "解答的邊界",
      "en-US": "The Riddle's Limit",
      "ja-JP": "謎の境界線",
      "ko-KR": "해답의 경계"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1568",
    "names": {
      "zh-CN": "昨日雨声轻",
      "zh-TW": "昨日雨聲輕",
      "en-US": "The Soft Rain of Yesterday",
      "ja-JP": "昨日の雨音は軽く",
      "ko-KR": "어제의 가벼운 빗소리"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1569",
    "names": {
      "zh-CN": "蜕至我为我",
      "zh-TW": "蛻至我為我",
      "en-US": "Until I Am Me",
      "ja-JP": "私が「私」になるまで",
      "ko-KR": "허물을 벗어 내가 되리라"
    },
    "rarity": 5,
    "released": false
  },
  {
    "id": "1570",
    "names": {
      "zh-CN": "圣歌应缄默",
      "zh-TW": "聖歌應緘默",
      "en-US": "The Silent Anthem",
      "ja-JP": "沈黙のアンセム",
      "ko-KR": "성가는 침묵하라"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1448",
    "names": {
      "zh-CN": "成长阵痛",
      "zh-TW": "成長陣痛",
      "en-US": "Growing Pains",
      "ja-JP": "成長の痛み",
      "ko-KR": "성장통"
    },
    "rarity": 4,
    "released": true
  },
  {
    "id": "1573",
    "names": {
      "zh-CN": "光之外的梦",
      "zh-TW": "A Dream Beyond Light",
      "en-US": "A Dream Beyond Light",
      "ja-JP": "光の彼方にある夢",
      "ko-KR": "A Dream Beyond Light"
    },
    "rarity": 5,
    "released": false
  },
  {
    "id": "1574",
    "names": {
      "zh-CN": "光影的栖所",
      "zh-TW": "Where Light and Shadows Rest",
      "en-US": "Where Light and Shadows Rest",
      "ja-JP": "光と影の棲家",
      "ko-KR": "Where Light and Shadows Rest"
    },
    "rarity": 5,
    "released": false
  },
  {
    "id": "1449",
    "names": {
      "zh-CN": "暂别旧夜",
      "zh-TW": "Farewell to the Old Night",
      "en-US": "Farewell to the Old Night",
      "ja-JP": "古き夜に別れを",
      "ko-KR": "Farewell to the Old Night"
    },
    "rarity": 4,
    "released": false
  },
  {
    "id": "1571",
    "names": {
      "zh-CN": "艺术原子能",
      "zh-TW": "藝術原子能",
      "en-US": "The Art of Atoms",
      "ja-JP": "原子の芸術",
      "ko-KR": "예술 원자력"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1572",
    "names": {
      "zh-CN": "科学编舞法",
      "zh-TW": "科學編舞法",
      "en-US": "The Dance of Science",
      "ja-JP": "科学の振付",
      "ko-KR": "과학 안무법"
    },
    "rarity": 5,
    "released": true
  },
  {
    "id": "1450",
    "names": {
      "zh-CN": "以饰真相",
      "zh-TW": "Dressing Up the Truth",
      "en-US": "Dressing Up the Truth",
      "ja-JP": "Dressing Up the Truth",
      "ko-KR": "Dressing Up the Truth"
    },
    "rarity": 4,
    "released": false
  },
  {
    "id": "1575",
    "names": {
      "zh-CN": "宣告以弦鸣",
      "zh-TW": "Arrow of Verdict",
      "en-US": "Arrow of Verdict",
      "ja-JP": "Arrow of Verdict",
      "ko-KR": "Arrow of Verdict"
    },
    "rarity": 5,
    "released": false
  },
  {
    "id": "1576",
    "names": {
      "zh-CN": "拢于心潮间",
      "zh-TW": "Tides Held Within",
      "en-US": "Tides Held Within",
      "ja-JP": "Tides Held Within",
      "ko-KR": "Tides Held Within"
    },
    "rarity": 5,
    "released": false
  }
];
